#pragma once
#include "ModuleMain.h"
#include <Aurie/shared.hpp>
#include <YYToolkit/YYTK_Shared.hpp>

enum locationIndexEnum;

enum itemIndexEnum
{
	itemIndexEnum_HoloHouse = 1,
	itemIndexEnum_HoloCoin,
	itemIndexEnum_ProgressiveStage,
	itemIndexEnum_TimeStage1,
	itemIndexEnum_AmeliaWatson = 100,
	itemIndexEnum_GawrGura,
	itemIndexEnum_NinomaeInanis,
	itemIndexEnum_TakanashiKiara,
	itemIndexEnum_MoriCalliope,
	itemIndexEnum_HakosBaelz,
	itemIndexEnum_OuroKronii,
	itemIndexEnum_CeresFauna,
	itemIndexEnum_NanashiMumei,
	itemIndexEnum_TsukumoSana,
	itemIndexEnum_IRyS,
	itemIndexEnum_ShirakamiFubuki,
	itemIndexEnum_OokamiMio,
	itemIndexEnum_NekomataOkayu,
	itemIndexEnum_InugamiKorone,
	itemIndexEnum_TokinoSora,
	itemIndexEnum_AZki,
	itemIndexEnum_RobocoSan,
	itemIndexEnum_HoshimachiSuisei,
	itemIndexEnum_SakuraMiko,
	itemIndexEnum_AkaiHaato,
	itemIndexEnum_YozoraMel,
	itemIndexEnum_NatsuiroMatsuri,
	itemIndexEnum_AkiRosenthal,
	itemIndexEnum_OozoraSubaru,
	itemIndexEnum_YuzukiChoco,
	itemIndexEnum_MurasakiShion,
	itemIndexEnum_NakiriAyame,
	itemIndexEnum_MinatoAqua,
	itemIndexEnum_MoonaHoshinova,
	itemIndexEnum_AyundaRisu,
	itemIndexEnum_AiraniIofifteen,
	itemIndexEnum_KureijiOllie,
	itemIndexEnum_PavoliaReine,
	itemIndexEnum_AnyaMelfissa,
	itemIndexEnum_KoboKanaeru,
	itemIndexEnum_KaelaKovalskia,
	itemIndexEnum_VestiaZeta,
	itemIndexEnum_UsadaPekora,
	itemIndexEnum_HoushouMarine,
	itemIndexEnum_ShiroganeNoel,
	itemIndexEnum_ShiranuiFlare,
	itemIndexEnum_KiryuCoco,
	itemIndexEnum_AmaneKanata,
	itemIndexEnum_TokoyamiTowa,
	itemIndexEnum_TsunomakiWatame,
	itemIndexEnum_HimemoriLuna,
	itemIndexEnum_WamyWater = 1000,
	itemIndexEnum_PsychoAxe,
	itemIndexEnum_XPotato,
	itemIndexEnum_BounceBall,
	itemIndexEnum_Sausage,
	itemIndexEnum_Glowstick,
	itemIndexEnum_SpiderCooking,
	itemIndexEnum_PlugTypeAsacoco,
	itemIndexEnum_BLBook,
	itemIndexEnum_EliteLava,
	itemIndexEnum_HoloBomb,
	itemIndexEnum_CuttingBoard,
	itemIndexEnum_FanBeam,
	itemIndexEnum_IdolSong,
	itemIndexEnum_CEOTears,
	itemIndexEnum_ENCurse,
	itemIndexEnum_OwlDagger,
	itemIndexEnum_EnergyDrink = 2000,
	itemIndexEnum_Plushie,
	itemIndexEnum_Limiter,
	itemIndexEnum_Beetle,
	itemIndexEnum_Shackles,
	itemIndexEnum_NinjaHeadband,
	itemIndexEnum_ChickenFeather,
	itemIndexEnum_RavenFeather,
	itemIndexEnum_BodyPillow,
	itemIndexEnum_FullMeal,
	itemIndexEnum_PikiPikiPiman,
	itemIndexEnum_NurseHorn,
	itemIndexEnum_Headphones,
	itemIndexEnum_UberSheep,
	itemIndexEnum_KnightlyMilk,
	itemIndexEnum_Sake,
	itemIndexEnum_FaceMask,
	itemIndexEnum_CreditCard,
	itemIndexEnum_GorillaPaw,
	itemIndexEnum_SuperChattoTime,
	itemIndexEnum_Halu,
	itemIndexEnum_InjectionTypeAsacoco,
	itemIndexEnum_IdolCostume,
	itemIndexEnum_GWSPill,
	itemIndexEnum_JustBandage,
	itemIndexEnum_Breastplate,
	itemIndexEnum_StudyGlasses,
	itemIndexEnum_BlacksmithGear,
	itemIndexEnum_HopeSoda,
	itemIndexEnum_StolenPiggyBank,
	itemIndexEnum_CandyKingdomSweets,
	itemIndexEnum_ResearcherCoat,
	itemIndexEnum_Membership,
	itemIndexEnum_DevilHat,
	itemIndexEnum_FocusShades,
	itemIndexEnum_CorporationPin,
	itemIndexEnum_PromiseTiara,
	itemIndexEnum_SpecialAttackShopUpgrade = 3000,
	itemIndexEnum_GrowthProgressiveShopUpgrade,
	itemIndexEnum_RerollProgressiveShopUpgrade,
	itemIndexEnum_EliminateProgressiveShopUpgrade,
	itemIndexEnum_HoldProgressiveShopUpgrade,
	itemIndexEnum_CustomizeShopUpgrade,
	itemIndexEnum_SupportsShopUpgrade,
	itemIndexEnum_MaterialShopUpgrade,
	itemIndexEnum_StampsShopUpgrade,
	itemIndexEnum_EnchantmentsShopUpgrade,
	itemIndexEnum_FandomShopUpgrade,
	itemIndexEnum_FanLettersShopUpgrade,
	itemIndexEnum_MaxHPProgressiveShopUpgrade,
	itemIndexEnum_ATKProgressiveShopUpgrade,
	itemIndexEnum_SPDProgressiveShopUpgrade,
	itemIndexEnum_CritProgressiveShopUpgrade,
	itemIndexEnum_PickUpProgressiveShopUpgrade,
	itemIndexEnum_HasteProgressiveShopUpgrade,
	itemIndexEnum_RegenProgressiveShopUpgrade,
	itemIndexEnum_DefenseProgressiveShopUpgrade,
	itemIndexEnum_SpecialCooldownProgressiveShopUpgrade,
	itemIndexEnum_SkillUpProgressiveShopUpgrade,
	itemIndexEnum_EXPGainProgressiveShopUpgrade,
	itemIndexEnum_FoodDropProgressiveShopUpgrade,
	itemIndexEnum_MoneyGainProgressiveShopUpgrade,
	itemIndexEnum_EnhancementProgressiveShopUpgrade,
	itemIndexEnum_MarketingProgressiveShopUpgrade,
};

void sendAPCheck(CInstance* Self, locationIndexEnum sendLocationIndex);
void loggingCallback(std::string logMessage);

bool CreateDeviceD3D(HWND hWnd);
void CleanupDeviceD3D();
void CreateRenderTarget();
void CleanupRenderTarget();
void renderImguiWindow(CInstance* Self);

void initArchipelago();
void loadModImguiMenu();