#include "Constants.h"

#include <unordered_set>

std::unordered_map<itemIndexEnum, std::string> weaponToIDMap
{
	{ itemIndexEnum_WamyWater, "WamyWater" },
	{ itemIndexEnum_PsychoAxe, "PsychoAxe" },
	{ itemIndexEnum_XPotato, "XPotato" },
	{ itemIndexEnum_BounceBall, "BounceBall" },
	{ itemIndexEnum_Sausage, "Sausage" },
	{ itemIndexEnum_Glowstick, "Glowstick" },
	{ itemIndexEnum_SpiderCooking, "SpiderCooking" },
	{ itemIndexEnum_PlugTypeAsacoco, "Tailplug" },
	{ itemIndexEnum_BLBook, "BLBook" },
	{ itemIndexEnum_EliteLava, "EliteLava" },
	{ itemIndexEnum_HoloBomb, "HoloBomb" },
	{ itemIndexEnum_CuttingBoard, "CuttingBoard" },
	{ itemIndexEnum_FanBeam, "HoloLaser" },
	{ itemIndexEnum_IdolSong, "IdolSong" },
	{ itemIndexEnum_CEOTears, "CEOTears" },
	{ itemIndexEnum_ENCurse, "ENCurse" },
	{ itemIndexEnum_OwlDagger, "OwlDagger" },
};

std::unordered_map<itemIndexEnum, std::string> itemToIDMap
{
	{ itemIndexEnum_EnergyDrink, "EnergyDrink" },
	{ itemIndexEnum_Plushie, "Plushie" },
	{ itemIndexEnum_Limiter, "Limiter" },
	{ itemIndexEnum_Beetle, "Beetle" },
	{ itemIndexEnum_Shackles, "Shacklesss" },
	{ itemIndexEnum_NinjaHeadband, "NinjaHeadband" },
	{ itemIndexEnum_ChickenFeather, "ChickensFeather" },
	{ itemIndexEnum_RavenFeather, "RavenFeather" },
	{ itemIndexEnum_BodyPillow, "BodyPillow" },
	{ itemIndexEnum_FullMeal, "FullMeal" },
	{ itemIndexEnum_PikiPikiPiman, "PikiPikiPiman" },
	{ itemIndexEnum_NurseHorn, "SuccubusHorn" },
	{ itemIndexEnum_Headphones, "Headphones" },
	{ itemIndexEnum_UberSheep, "UberSheep" },
	{ itemIndexEnum_KnightlyMilk, "HolyMilk" },
	{ itemIndexEnum_Sake, "Sake" },
	{ itemIndexEnum_FaceMask, "FaceMask" },
	{ itemIndexEnum_CreditCard, "CreditCard" },
	{ itemIndexEnum_GorillaPaw, "GorillasPaw" },
	{ itemIndexEnum_SuperChattoTime, "SuperChattoTime" },
	{ itemIndexEnum_Halu, "Halu" },
	{ itemIndexEnum_InjectionTypeAsacoco, "InjectionAsacoco" },
	{ itemIndexEnum_IdolCostume, "IdolCostume" },
	{ itemIndexEnum_GWSPill, "GWSPill" },
	{ itemIndexEnum_JustBandage, "Bandaid" },
	{ itemIndexEnum_Breastplate, "Breastplate" },
	{ itemIndexEnum_StudyGlasses, "StudyGlasses" },
	{ itemIndexEnum_BlacksmithGear, "BlacksmithsGear" },
	{ itemIndexEnum_HopeSoda, "HopeSoda" },
	{ itemIndexEnum_StolenPiggyBank, "PiggyBank" },
	{ itemIndexEnum_CandyKingdomSweets, "Candy" },
	{ itemIndexEnum_ResearcherCoat, "LabCoat" },
	{ itemIndexEnum_Membership, "Membership" },
	{ itemIndexEnum_DevilHat, "DevilHat" },
	{ itemIndexEnum_FocusShades, "FocusShades" },
	{ itemIndexEnum_CorporationPin, "CorporationPin" },
	{ itemIndexEnum_PromiseTiara, "PromiseTiara" },
};

std::unordered_map<itemIndexEnum, std::string> shopToIDMap
{
	{ itemIndexEnum_SpecialAttackShopUpgrade, "specUnlock" },
	{ itemIndexEnum_GrowthProgressiveShopUpgrade, "growth" },
	{ itemIndexEnum_RerollProgressiveShopUpgrade, "reroll" },
	{ itemIndexEnum_EliminateProgressiveShopUpgrade, "eliminate" },
	{ itemIndexEnum_HoldProgressiveShopUpgrade, "holdOption" },
	{ itemIndexEnum_CustomizeShopUpgrade, "canDisable" },
	{ itemIndexEnum_SupportsShopUpgrade, "supports" },
	{ itemIndexEnum_MaterialShopUpgrade, "materialDrops" },
	{ itemIndexEnum_StampsShopUpgrade, "stamps" },
	{ itemIndexEnum_EnchantmentsShopUpgrade, "enchantments" },
	{ itemIndexEnum_FandomShopUpgrade, "fandom" },
	{ itemIndexEnum_FanLettersShopUpgrade, "fanLetterUnlock" },
	{ itemIndexEnum_MaxHPProgressiveShopUpgrade, "HP" },
	{ itemIndexEnum_ATKProgressiveShopUpgrade, "ATK" },
	{ itemIndexEnum_SPDProgressiveShopUpgrade, "SPD" },
	{ itemIndexEnum_CritProgressiveShopUpgrade, "crit" },
	{ itemIndexEnum_PickUpProgressiveShopUpgrade, "pickupRange" },
	{ itemIndexEnum_HasteProgressiveShopUpgrade, "haste" },
	{ itemIndexEnum_RegenProgressiveShopUpgrade, "regen" },
	{ itemIndexEnum_DefenseProgressiveShopUpgrade, "DR" },
	{ itemIndexEnum_SpecialCooldownProgressiveShopUpgrade, "specCDR" },
	{ itemIndexEnum_SkillUpProgressiveShopUpgrade, "skillDamage" },
	{ itemIndexEnum_EXPGainProgressiveShopUpgrade, "EXP" },
	{ itemIndexEnum_FoodDropProgressiveShopUpgrade, "food" },
	{ itemIndexEnum_MoneyGainProgressiveShopUpgrade, "moneyGain" },
	{ itemIndexEnum_EnhancementProgressiveShopUpgrade, "enhanceUp" },
	{ itemIndexEnum_MarketingProgressiveShopUpgrade, "mobUp" },
};

std::unordered_map<std::string, itemIndexEnum> shopIDToIndexMap
{
	{ "specUnlock", itemIndexEnum_SpecialAttackShopUpgrade },
	{ "growth", itemIndexEnum_GrowthProgressiveShopUpgrade },
	{ "reroll", itemIndexEnum_RerollProgressiveShopUpgrade },
	{ "eliminate", itemIndexEnum_EliminateProgressiveShopUpgrade },
	{ "holdOption", itemIndexEnum_HoldProgressiveShopUpgrade },
	{ "canDisable", itemIndexEnum_CustomizeShopUpgrade },
	{ "supports", itemIndexEnum_SupportsShopUpgrade },
	{ "materialDrops", itemIndexEnum_MaterialShopUpgrade },
	{ "stamps", itemIndexEnum_StampsShopUpgrade },
	{ "enchantments", itemIndexEnum_EnchantmentsShopUpgrade },
	{ "fandom", itemIndexEnum_FandomShopUpgrade },
	{ "fanLetterUnlock", itemIndexEnum_FanLettersShopUpgrade },
	{ "HP", itemIndexEnum_MaxHPProgressiveShopUpgrade },
	{ "ATK", itemIndexEnum_ATKProgressiveShopUpgrade },
	{ "SPD", itemIndexEnum_SPDProgressiveShopUpgrade },
	{ "crit", itemIndexEnum_CritProgressiveShopUpgrade },
	{ "pickupRange", itemIndexEnum_PickUpProgressiveShopUpgrade },
	{ "haste", itemIndexEnum_HasteProgressiveShopUpgrade },
	{ "regen", itemIndexEnum_RegenProgressiveShopUpgrade },
	{ "DR", itemIndexEnum_DefenseProgressiveShopUpgrade },
	{ "specCDR", itemIndexEnum_SpecialCooldownProgressiveShopUpgrade },
	{ "skillDamage", itemIndexEnum_SkillUpProgressiveShopUpgrade },
	{ "EXP", itemIndexEnum_EXPGainProgressiveShopUpgrade },
	{ "food", itemIndexEnum_FoodDropProgressiveShopUpgrade },
	{ "moneyGain", itemIndexEnum_MoneyGainProgressiveShopUpgrade },
	{ "enhanceUp", itemIndexEnum_EnhancementProgressiveShopUpgrade },
	{ "mobUp", itemIndexEnum_MarketingProgressiveShopUpgrade },
};

std::unordered_map<itemIndexEnum, std::string> itemToNameMap
{
	{ itemIndexEnum_HoloHouse, "HoloHouse" },
	{ itemIndexEnum_HoloCoin, "HoloCoin" },
	{ itemIndexEnum_ProgressiveStage, "Progressive Stage" },
	{ itemIndexEnum_ProgressiveStageHard, "Progressive Stage (HARD)" },
	{ itemIndexEnum_TimeStage1, "Time Stage 1" },
	{ itemIndexEnum_AmeliaWatson, "Amelia Watson" },
	{ itemIndexEnum_GawrGura, "Gawr Gura" },
	{ itemIndexEnum_NinomaeInanis, "Ninomae Inanis" },
	{ itemIndexEnum_TakanashiKiara, "Takanashi Kiara" },
	{ itemIndexEnum_MoriCalliope, "Mori Calliope" },
	{ itemIndexEnum_HakosBaelz, "Hakos Baelz" },
	{ itemIndexEnum_OuroKronii, "Ouro Kronii" },
	{ itemIndexEnum_CeresFauna, "Ceres Fauna" },
	{ itemIndexEnum_NanashiMumei, "Nanashi Mumei" },
	{ itemIndexEnum_TsukumoSana, "Tsukumo Sana" },
	{ itemIndexEnum_IRyS, "IRyS" },
	{ itemIndexEnum_ShirakamiFubuki, "Shirakami Fubuki" },
	{ itemIndexEnum_OokamiMio, "Ookami Mio" },
	{ itemIndexEnum_NekomataOkayu, "Nekomata Okayu" },
	{ itemIndexEnum_InugamiKorone, "Inugami Korone" },
	{ itemIndexEnum_TokinoSora, "Tokino Sora" },
	{ itemIndexEnum_AZki, "AZki" },
	{ itemIndexEnum_RobocoSan, "Roboco-san" },
	{ itemIndexEnum_HoshimachiSuisei, "Hoshimachi Suisei" },
	{ itemIndexEnum_SakuraMiko, "Sakura Miko" },
	{ itemIndexEnum_AkaiHaato, "Akai Haato" },
	{ itemIndexEnum_YozoraMel, "Yozora Mel" },
	{ itemIndexEnum_NatsuiroMatsuri, "Natsuiro Matsuri" },
	{ itemIndexEnum_AkiRosenthal, "Aki Rosenthal" },
	{ itemIndexEnum_YuzukiChoco, "Yuzuki Choco" },
	{ itemIndexEnum_OozoraSubaru, "Oozora Subaru" },
	{ itemIndexEnum_MurasakiShion, "Murasaki Shion" },
	{ itemIndexEnum_NakiriAyame, "Nakiri Ayame" },
	{ itemIndexEnum_MinatoAqua, "Minato Aqua" },
	{ itemIndexEnum_MoonaHoshinova, "Moona Hoshinova" },
	{ itemIndexEnum_AiraniIofifteen, "Airani Iofifteen" },
	{ itemIndexEnum_AyundaRisu, "Ayunda Risu" },
	{ itemIndexEnum_KureijiOllie, "Kureiji Ollie" },
	{ itemIndexEnum_PavoliaReine, "Pavolia Reine" },
	{ itemIndexEnum_AnyaMelfissa, "Anya Melfissa" },
	{ itemIndexEnum_KoboKanaeru, "Kobo Kanaeru" },
	{ itemIndexEnum_KaelaKovalskia, "Kaela Kovalskia" },
	{ itemIndexEnum_VestiaZeta, "Vestia Zeta" },
	{ itemIndexEnum_UsadaPekora, "Usada Pekora" },
	{ itemIndexEnum_ShiroganeNoel, "Shirogane Noel" },
	{ itemIndexEnum_ShiranuiFlare, "Shiranui Flare" },
	{ itemIndexEnum_HoushouMarine, "Houshou Marine" },
	{ itemIndexEnum_KiryuCoco, "Kiryu Coco" },
	{ itemIndexEnum_AmaneKanata, "Amane Kanata" },
	{ itemIndexEnum_TsunomakiWatame, "Tsunomaki Watame" },
	{ itemIndexEnum_TokoyamiTowa, "Tokoyami Towa" },
	{ itemIndexEnum_HimemoriLuna, "Himemori Luna" },
	{ itemIndexEnum_WamyWater, "Wamy Water" },
	{ itemIndexEnum_PsychoAxe, "Psycho Axe" },
	{ itemIndexEnum_XPotato, "X-Potato" },
	{ itemIndexEnum_BounceBall, "Bounce Ball" },
	{ itemIndexEnum_Sausage, "Sausage" },
	{ itemIndexEnum_Glowstick, "Glowstick" },
	{ itemIndexEnum_SpiderCooking, "Spider Cooking" },
	{ itemIndexEnum_PlugTypeAsacoco, "Plug Type Asacoco" },
	{ itemIndexEnum_BLBook, "BL Book" },
	{ itemIndexEnum_EliteLava, "Elite Lava Bucket" },
	{ itemIndexEnum_HoloBomb, "Holo Bomb" },
	{ itemIndexEnum_CuttingBoard, "Cutting Board" },
	{ itemIndexEnum_FanBeam, "Fan Beam" },
	{ itemIndexEnum_IdolSong, "Idol Song" },
	{ itemIndexEnum_CEOTears, "CEO's Tears" },
	{ itemIndexEnum_ENCurse, "EN's Curse" },
	{ itemIndexEnum_OwlDagger, "Owl Dagger" },
	{ itemIndexEnum_EnergyDrink, "Energy Drink" },
	{ itemIndexEnum_Plushie, "Plushie" },
	{ itemIndexEnum_Limiter, "Limiter" },
	{ itemIndexEnum_Beetle, "Beetle" },
	{ itemIndexEnum_Shackles, "Kusogaki Shackles" },
	{ itemIndexEnum_NinjaHeadband, "Ninja Headband" },
	{ itemIndexEnum_ChickenFeather, "Chicken's Feather" },
	{ itemIndexEnum_RavenFeather, "Raven Feather" },
	{ itemIndexEnum_BodyPillow, "Body Pillow" },
	{ itemIndexEnum_FullMeal, "Full Meal" },
	{ itemIndexEnum_PikiPikiPiman, "Piki Piki Piman" },
	{ itemIndexEnum_NurseHorn, "Nurse's Horn" },
	{ itemIndexEnum_Headphones, "Headphones" },
	{ itemIndexEnum_UberSheep, "Uber Sheep" },
	{ itemIndexEnum_KnightlyMilk, "Knightly Milk" },
	{ itemIndexEnum_Sake, "Sake" },
	{ itemIndexEnum_FaceMask, "Face Mask" },
	{ itemIndexEnum_CreditCard, "Credit Card" },
	{ itemIndexEnum_GorillaPaw, "Gorilla's Paw" },
	{ itemIndexEnum_SuperChattoTime, "Super Chatto Time!" },
	{ itemIndexEnum_Halu, "Halu" },
	{ itemIndexEnum_InjectionTypeAsacoco, "Injection Type Asacoco" },
	{ itemIndexEnum_IdolCostume, "Idol Costume" },
	{ itemIndexEnum_GWSPill, "GWS Pill" },
	{ itemIndexEnum_JustBandage, "Just Bandage" },
	{ itemIndexEnum_Breastplate, "Breastplate" },
	{ itemIndexEnum_StudyGlasses, "Study Glasses" },
	{ itemIndexEnum_BlacksmithGear, "Blacksmith's Gear" },
	{ itemIndexEnum_HopeSoda, "Hope Soda" },
	{ itemIndexEnum_StolenPiggyBank, "Stolen Piggy Bank" },
	{ itemIndexEnum_CandyKingdomSweets, "Candy Kingdom Sweets" },
	{ itemIndexEnum_ResearcherCoat, "Researcher's Coat" },
	{ itemIndexEnum_Membership, "Membership" },
	{ itemIndexEnum_DevilHat, "Devil Hat" },
	{ itemIndexEnum_FocusShades, "Focus Shades" },
	{ itemIndexEnum_CorporationPin, "Corporation Pin" },
	{ itemIndexEnum_PromiseTiara, "Promise Tiara" },
	{ itemIndexEnum_SpecialAttackShopUpgrade, "Special Attack Shop Upgrade" },
	{ itemIndexEnum_GrowthProgressiveShopUpgrade, "Growth Progressive Shop Upgrade" },
	{ itemIndexEnum_RerollProgressiveShopUpgrade, "Reroll Progressive Shop Upgrade" },
	{ itemIndexEnum_EliminateProgressiveShopUpgrade, "Eliminate Progressive Shop Upgrade" },
	{ itemIndexEnum_HoldProgressiveShopUpgrade, "Hold Progressive Shop Upgrade" },
	{ itemIndexEnum_CustomizeShopUpgrade, "Customize Shop Upgrade" },
	{ itemIndexEnum_SupportsShopUpgrade, "Supports Shop Upgrade" },
	{ itemIndexEnum_MaterialShopUpgrade, "Material Find Shop Upgrade" },
	{ itemIndexEnum_StampsShopUpgrade, "Stamps Shop Upgrade" },
	{ itemIndexEnum_EnchantmentsShopUpgrade, "Enchantments Shop Upgrade" },
	{ itemIndexEnum_FandomShopUpgrade, "Fandom Shop Upgrade" },
	{ itemIndexEnum_FanLettersShopUpgrade, "Fan Letters Shop Upgrade" },
	{ itemIndexEnum_MaxHPProgressiveShopUpgrade, "Max HP Progressive Shop Upgrade" },
	{ itemIndexEnum_ATKProgressiveShopUpgrade, "ATK Progressive Shop Upgrade" },
	{ itemIndexEnum_SPDProgressiveShopUpgrade, "SPD Progressive Shop Upgrade" },
	{ itemIndexEnum_CritProgressiveShopUpgrade, "Crit Progressive Shop Upgrade" },
	{ itemIndexEnum_PickUpProgressiveShopUpgrade, "Pick Up Range Progressive Shop Upgrade" },
	{ itemIndexEnum_HasteProgressiveShopUpgrade, "Haste Up Progressive Shop Upgrade" },
	{ itemIndexEnum_RegenProgressiveShopUpgrade, "Regen Progressive Shop Upgrade" },
	{ itemIndexEnum_DefenseProgressiveShopUpgrade, "Defense Progressive Shop Upgrade" },
	{ itemIndexEnum_SpecialCooldownProgressiveShopUpgrade, "Special Cooldown Reduction Progressive Shop Upgrade" },
	{ itemIndexEnum_SkillUpProgressiveShopUpgrade, "Skill Up Progressive Shop Upgrade" },
	{ itemIndexEnum_EXPGainProgressiveShopUpgrade, "EXP Gain Up Progressive Shop Upgrade" },
	{ itemIndexEnum_FoodDropProgressiveShopUpgrade, "Food Drops Up Progressive Shop Upgrade" },
	{ itemIndexEnum_MoneyGainProgressiveShopUpgrade, "Money Gain Up Progressive Shop Upgrade" },
	{ itemIndexEnum_EnhancementProgressiveShopUpgrade, "Enhancement Rate Up Progressive Shop Upgrade" },
	{ itemIndexEnum_MarketingProgressiveShopUpgrade, "Marketing Up Progressive Shop Upgrade" },
	{ itemIndexEnum_StandardSoil, "Standard Soil" },
	{ itemIndexEnum_ExpeditedSoil, "Expedited Soil" },
	{ itemIndexEnum_EnhancedSoil, "Enhanced Soil" },
	{ itemIndexEnum_WheatSeed, "Wheat Seed" },
	{ itemIndexEnum_TomatoSeed, "Tomato Seed" },
	{ itemIndexEnum_PotatoSeed, "Potato Seed" },
	{ itemIndexEnum_RiceSeed, "Rice Seed" },
	{ itemIndexEnum_OnionSeed, "Onion Seed" },
	{ itemIndexEnum_CarrotSeed, "Carrot Seed" },
	{ itemIndexEnum_GreenBeanSeed, "Green Bean Seed" },
	{ itemIndexEnum_PepperSeed, "Pepper Seed" },
	{ itemIndexEnum_StrawberrySeed, "Strawberry Seed" },
	{ itemIndexEnum_CornSeed, "Corn Seed" },
	{ itemIndexEnum_RadishSeed, "Radish Seed" },
	{ itemIndexEnum_GarlicSeed, "Garlic Seed" },
	{ itemIndexEnum_ProgressiveRod, "Progressive Rod" },
	{ itemIndexEnum_ProgressiveAxe, "Progressive Axe" },
	{ itemIndexEnum_ProgressivePickaxe, "Progressive Pickaxe" },
};

std::unordered_set<locationIndexEnum> grindyLocations
{
	locationIndexEnum_AmeliaWastonGachikoi,
	locationIndexEnum_GawrGuraGachikoi,
	locationIndexEnum_NinomaeInanisGachikoi,
	locationIndexEnum_TakanshiKiaraGachikoi,
	locationIndexEnum_MoriCalliopeGachikoi,
	locationIndexEnum_HakosBaelzGachikoi,
	locationIndexEnum_OuroKroniiGachikoi,
	locationIndexEnum_CeresFaunaGachikoi,
	locationIndexEnum_NanashiMumeiGachikoi,
	locationIndexEnum_TsukumoSanaGachikoi,
	locationIndexEnum_IRySGachikoi,
	locationIndexEnum_ShirakamiFubukiGachikoi,
	locationIndexEnum_OokamiMioGachikoi,
	locationIndexEnum_NekomataOkayuGachikoi,
	locationIndexEnum_InugamiKoroneGachikoi,
	locationIndexEnum_TokinoSoraGachikoi,
	locationIndexEnum_AZkiGachikoi,
	locationIndexEnum_RobocoGachikoi,
	locationIndexEnum_HoshimachiSuiseiGachikoi,
	locationIndexEnum_SakuraMikoGachikoi,
	locationIndexEnum_AkaiHaatoGachikoi,
	locationIndexEnum_YozoraMelGachikoi,
	locationIndexEnum_NatsuiroMatsuriGachikoi,
	locationIndexEnum_AkiRosenthalGachikoi,
	locationIndexEnum_YuzukiChocoGachikoi,
	locationIndexEnum_OozoraSubaruGachikoi,
	locationIndexEnum_MurasakiShionGachikoi,
	locationIndexEnum_NakiriAyameGachikoi,
	locationIndexEnum_MinatoAquaGachikoi,
	locationIndexEnum_MoonaHoshinovaGachikoi,
	locationIndexEnum_AiraniIofifteenGachikoi,
	locationIndexEnum_AyundaRisuGachikoi,
	locationIndexEnum_KureijiOllieGachikoi,
	locationIndexEnum_PavoliaReineGachikoi,
	locationIndexEnum_AnyaMelfissaGachikoi,
	locationIndexEnum_KoboKanaeruGachikoi,
	locationIndexEnum_KaelaKovalskiaGachikoi,
	locationIndexEnum_VestiaZetaGachikoi,
	locationIndexEnum_UsadaPekoraGachikoi,
	locationIndexEnum_ShiroganeNoelGachikoi,
	locationIndexEnum_ShiranuiFlareGachikoi,
	locationIndexEnum_HoushouMarineGachikoi,
	locationIndexEnum_KiryuCocoGachikoi,
	locationIndexEnum_AmaneKanataGachikoi,
	locationIndexEnum_TsunomakiWatameGachikoi,
	locationIndexEnum_TokoyamiTowaGachikoi,
	locationIndexEnum_HimemoriLunaGachikoi,
	locationIndexEnum_ClearTowerOfSuffering,
	locationIndexEnum_GetSomeHelp,
};

std::unordered_set<locationIndexEnum> stageLocations
{
	locationIndexEnum_AmeliaWastonStageClear,
	locationIndexEnum_AmeliaWastonGachikoi,
	locationIndexEnum_GawrGuraStageClear,
	locationIndexEnum_GawrGuraGachikoi,
	locationIndexEnum_NinomaeInanis10Minutes,
	locationIndexEnum_NinomaeInanisStageClear,
	locationIndexEnum_NinomaeInanisGachikoi,
	locationIndexEnum_TakanshiKiara10Minutes,
	locationIndexEnum_TakanshiKiaraStageClear,
	locationIndexEnum_TakanshiKiaraGachikoi,
	locationIndexEnum_MoriCalliope10Minutes,
	locationIndexEnum_MoriCalliopeStageClear,
	locationIndexEnum_MoriCalliopeGachikoi,
	locationIndexEnum_HakosBaelz10Minutes,
	locationIndexEnum_HakosBaelzStageClear,
	locationIndexEnum_HakosBaelzGachikoi,
	locationIndexEnum_OuroKroniiStageClear,
	locationIndexEnum_OuroKroniiGachikoi,
	locationIndexEnum_CeresFaunaStageClear,
	locationIndexEnum_CeresFaunaGachikoi,
	locationIndexEnum_NanashiMumeiStageClear,
	locationIndexEnum_NanashiMumeiGachikoi,
	locationIndexEnum_TsukumoSana10Minutes,
	locationIndexEnum_TsukumoSanaStageClear,
	locationIndexEnum_TsukumoSanaGachikoi,
	locationIndexEnum_IRyS10Minutes,
	locationIndexEnum_IRySStageClear,
	locationIndexEnum_IRySGachikoi,
	locationIndexEnum_ShirakamiFubukiStageClear,
	locationIndexEnum_ShirakamiFubukiGachikoi,
	locationIndexEnum_OokamiMioStageClear,
	locationIndexEnum_OokamiMioGachikoi,
	locationIndexEnum_NekomataOkayuStageClear,
	locationIndexEnum_NekomataOkayuGachikoi,
	locationIndexEnum_InugamiKorone10Minutes,
	locationIndexEnum_InugamiKoroneStageClear,
	locationIndexEnum_InugamiKoroneGachikoi,
	locationIndexEnum_TokinoSoraStageClear,
	locationIndexEnum_TokinoSoraGachikoi,
	locationIndexEnum_AZkiStageClear,
	locationIndexEnum_AZkiGachikoi,
	locationIndexEnum_RobocoStageClear,
	locationIndexEnum_RobocoGachikoi,
	locationIndexEnum_HoshimachiSuiseiStageClear,
	locationIndexEnum_HoshimachiSuiseiGachikoi,
	locationIndexEnum_SakuraMikoStageClear,
	locationIndexEnum_SakuraMikoGachikoi,
	locationIndexEnum_AkaiHaatoStageClear,
	locationIndexEnum_AkaiHaatoGachikoi,
	locationIndexEnum_YozoraMelStageClear,
	locationIndexEnum_YozoraMelGachikoi,
	locationIndexEnum_NatsuiroMatsuriStageClear,
	locationIndexEnum_NatsuiroMatsuriGachikoi,
	locationIndexEnum_AkiRosenthalStageClear,
	locationIndexEnum_AkiRosenthalGachikoi,
	locationIndexEnum_YuzukiChocoStageClear,
	locationIndexEnum_YuzukiChocoGachikoi,
	locationIndexEnum_OozoraSubaruStageClear,
	locationIndexEnum_OozoraSubaruGachikoi,
	locationIndexEnum_MurasakiShion10Minutes,
	locationIndexEnum_MurasakiShionStageClear,
	locationIndexEnum_MurasakiShionGachikoi,
	locationIndexEnum_NakiriAyameStageClear,
	locationIndexEnum_NakiriAyameGachikoi,
	locationIndexEnum_MinatoAquaStageClear,
	locationIndexEnum_MinatoAquaGachikoi,
	locationIndexEnum_MoonaHoshinovaStageClear,
	locationIndexEnum_MoonaHoshinovaGachikoi,
	locationIndexEnum_AiraniIofifteenStageClear,
	locationIndexEnum_AiraniIofifteenGachikoi,
	locationIndexEnum_AyundaRisuStageClear,
	locationIndexEnum_AyundaRisuGachikoi,
	locationIndexEnum_KureijiOllieStageClear,
	locationIndexEnum_KureijiOllie10Minutes,
	locationIndexEnum_KureijiOllieGachikoi,
	locationIndexEnum_PavoliaReineStageClear,
	locationIndexEnum_PavoliaReineGachikoi,
	locationIndexEnum_AnyaMelfissaStageClear,
	locationIndexEnum_AnyaMelfissaGachikoi,
	locationIndexEnum_KoboKanaeruStageClear,
	locationIndexEnum_KoboKanaeruGachikoi,
	locationIndexEnum_KaelaKovalskiaStageClear,
	locationIndexEnum_KaelaKovalskiaGachikoi,
	locationIndexEnum_VestiaZeta10Minutes,
	locationIndexEnum_VestiaZetaStageClear,
	locationIndexEnum_VestiaZetaGachikoi,
	locationIndexEnum_UsadaPekoraStageClear,
	locationIndexEnum_UsadaPekoraGachikoi,
	locationIndexEnum_ShiroganeNoelStageClear,
	locationIndexEnum_ShiroganeNoelGachikoi,
	locationIndexEnum_ShiranuiFlareStageClear,
	locationIndexEnum_ShiranuiFlareGachikoi,
	locationIndexEnum_HoushouMarineStageClear,
	locationIndexEnum_HoushouMarineGachikoi,
	locationIndexEnum_KiryuCocoStageClear,
	locationIndexEnum_KiryuCocoGachikoi,
	locationIndexEnum_AmaneKanataStageClear,
	locationIndexEnum_AmaneKanataGachikoi,
	locationIndexEnum_TsunomakiWatameStageClear,
	locationIndexEnum_TsunomakiWatameGachikoi,
	locationIndexEnum_TokoyamiTowaStageClear,
	locationIndexEnum_TokoyamiTowaGachikoi,
	locationIndexEnum_HimemoriLunaStageClear,
	locationIndexEnum_HimemoriLunaGachikoi,
	locationIndexEnum_FirstGame,
	locationIndexEnum_DefeatFubura,
	locationIndexEnum_DefeatStage1Boss,
	locationIndexEnum_DefeatStage2Boss,
	locationIndexEnum_DefeatStage3Boss,
	locationIndexEnum_DefeatStage4Boss,
	locationIndexEnum_DefeatStage5Boss,
	locationIndexEnum_DefeatStage1HardBoss,
	locationIndexEnum_DefeatStage2HardBoss,
	locationIndexEnum_DefeatStage3HardBoss,
	locationIndexEnum_DefeatStage4HardBoss,
	locationIndexEnum_ClearTimeMode,
	locationIndexEnum_UseSpecial,
	locationIndexEnum_DestroyYagooStatue,
	locationIndexEnum_UseAnvil,
	locationIndexEnum_CuttingBoard10Minutes,
	locationIndexEnum_UsePlugTypeAsacoco,
	locationIndexEnum_UseSake,
	locationIndexEnum_Level50,
	locationIndexEnum_Level100,
	locationIndexEnum_Defeat5000,
	locationIndexEnum_LoseWithHalu,
	locationIndexEnum_Eat50Hamburgers,
	locationIndexEnum_Deal1000Damage,
	locationIndexEnum_Deal10000Damage,
	locationIndexEnum_NoMove,
	locationIndexEnum_10Minutes,
	locationIndexEnum_NoSpecial,
	locationIndexEnum_UseSuperChattoTime,
	locationIndexEnum_PetBubba,
	locationIndexEnum_Get4Collabs,
	locationIndexEnum_Take500Damage,
	locationIndexEnum_EnhanceAWeapon,
	locationIndexEnum_DefeatYagoo,
	locationIndexEnum_DefeatGoldYagoo,
	locationIndexEnum_DefeatSilverYagoo,
	locationIndexEnum_LoseToYagoo,
	locationIndexEnum_SuperBox,
	locationIndexEnum_DropSuperItem,
	locationIndexEnum_ClearHardcore,
	locationIndexEnum_10Enhance,
	locationIndexEnum_MainWeaponOnly,
	locationIndexEnum_Fail5Enhance,
	locationIndexEnum_Fail1To2Enhance,
	locationIndexEnum_ClearHaluLevel5,
	locationIndexEnum_30MinutesHaluLevel5,
	locationIndexEnum_DefeatBossUnder10Seconds,
	locationIndexEnum_LeaveBossAlive5Minutes,
	locationIndexEnum_LevelUp5Times1Second,
	locationIndexEnum_CompleteArmory,
	locationIndexEnum_100Crit,
	locationIndexEnum_1MillionScore,
	locationIndexEnum_WatchTV10Seconds,
	locationIndexEnum_NoDamage5Minutes,
	locationIndexEnum_NoItems,
	locationIndexEnum_GoldHammer,
	locationIndexEnum_NoSkill,
	locationIndexEnum_HasteUp10,
	locationIndexEnum_IofiSpecial20Seconds,
	locationIndexEnum_FirstOptionOnly,
	locationIndexEnum_HardNoProjectiles,
	locationIndexEnum_MainWeaponLevel1Only,
	locationIndexEnum_ClearHardNoHealItems,
	locationIndexEnum_500HP,
	locationIndexEnum_10FanLetters,
	locationIndexEnum_Stage4HardNoQuestionsWrong,
	locationIndexEnum_Sell10Stamps,
	locationIndexEnum_500PickUpRange,
	locationIndexEnum_3DeathChickenFeather,
	locationIndexEnum_GetSomeHelp,
};

std::map<locationIndexEnum, std::string> locationToNameMap
{
	{ locationIndexEnum_AmeliaWastonStageClear, "Clear a Stage with Amelia Watson" },
	{ locationIndexEnum_AmeliaWastonGachikoi, "Reach Gachikoi with Amelia Watson" },
	{ locationIndexEnum_GawrGuraStageClear, "Clear a Stage with Gawr Gura" },
	{ locationIndexEnum_GawrGuraGachikoi, "Reach Gachikoi with Gawr Gura" },
	{ locationIndexEnum_NinomaeInanis10Minutes, "Reach 10 minutes with Ninomae Inanis" },
	{ locationIndexEnum_NinomaeInanisStageClear, "Clear a Stage with Ninomae Inanis" },
	{ locationIndexEnum_NinomaeInanisGachikoi, "Reach Gachikoi with Ninomae Inanis" },
	{ locationIndexEnum_TakanshiKiara10Minutes, "Reach 10 minutes with Takanashi Kiara" },
	{ locationIndexEnum_TakanshiKiaraStageClear, "Clear a Stage with Takanashi Kiara" },
	{ locationIndexEnum_TakanshiKiaraGachikoi, "Reach Gachikoi with Takanashi Kiara" },
	{ locationIndexEnum_MoriCalliope10Minutes, "Reach 10 minutes with Mori Calliope" },
	{ locationIndexEnum_MoriCalliopeStageClear, "Clear a Stage with Mori Calliope" },
	{ locationIndexEnum_MoriCalliopeGachikoi, "Reach Gachikoi with Mori Calliope" },
	{ locationIndexEnum_HakosBaelz10Minutes, "Reach 10 minutes with Hakos Baelz" },
	{ locationIndexEnum_HakosBaelzStageClear, "Clear a Stage with Hakos Baelz" },
	{ locationIndexEnum_HakosBaelzGachikoi, "Reach Gachikoi with Hakos Baelz" },
	{ locationIndexEnum_OuroKroniiStageClear, "Clear a Stage with Ouro Kronii" },
	{ locationIndexEnum_OuroKroniiGachikoi, "Reach Gachikoi with Ouro Kronii" },
	{ locationIndexEnum_CeresFaunaStageClear, "Clear a Stage with Ceres Fauna" },
	{ locationIndexEnum_CeresFaunaGachikoi, "Reach Gachikoi with Ceres Fauna" },
	{ locationIndexEnum_NanashiMumeiStageClear, "Clear a Stage with Nanashi Mumei" },
	{ locationIndexEnum_NanashiMumeiGachikoi, "Reach Gachikoi with Nanashi Mumei" },
	{ locationIndexEnum_TsukumoSana10Minutes, "Reach 10 minutes with Tsukumo Sana" },
	{ locationIndexEnum_TsukumoSanaStageClear, "Clear a Stage with Tsukumo Sana" },
	{ locationIndexEnum_TsukumoSanaGachikoi, "Reach Gachikoi with Tsukumo Sana" },
	{ locationIndexEnum_IRyS10Minutes, "Reach 10 minutes with IRyS" },
	{ locationIndexEnum_IRySStageClear, "Clear a Stage with IRyS" },
	{ locationIndexEnum_IRySGachikoi, "Reach Gachikoi with IRyS" },
	{ locationIndexEnum_ShirakamiFubukiStageClear, "Clear a Stage with Shirakami Fubuki" },
	{ locationIndexEnum_ShirakamiFubukiGachikoi, "Reach Gachikoi with Shirakami Fubuki" },
	{ locationIndexEnum_OokamiMioStageClear, "Clear a Stage with Ookami Mio" },
	{ locationIndexEnum_OokamiMioGachikoi, "Reach Gachikoi with Ookami Mio" },
	{ locationIndexEnum_NekomataOkayuStageClear, "Clear a Stage with Nekomata Okayu" },
	{ locationIndexEnum_NekomataOkayuGachikoi, "Reach Gachikoi with Nekomata Okayu" },
	{ locationIndexEnum_InugamiKorone10Minutes, "Reach 10 minutes with Inugami Korone" },
	{ locationIndexEnum_InugamiKoroneStageClear, "Clear a Stage with Inugami Korone" },
	{ locationIndexEnum_InugamiKoroneGachikoi, "Reach Gachikoi with Inugami Korone" },
	{ locationIndexEnum_TokinoSoraStageClear, "Clear a Stage with Tokino Sora" },
	{ locationIndexEnum_TokinoSoraGachikoi, "Reach Gachikoi with Tokino Sora" },
	{ locationIndexEnum_AZkiStageClear, "Clear a Stage with AZki" },
	{ locationIndexEnum_AZkiGachikoi, "Reach Gachikoi with AZki" },
	{ locationIndexEnum_RobocoStageClear, "Clear a Stage with Roboco-san" },
	{ locationIndexEnum_RobocoGachikoi, "Reach Gachikoi with Roboco-san" },
	{ locationIndexEnum_HoshimachiSuiseiStageClear, "Clear a Stage with Hoshimachi Suisei" },
	{ locationIndexEnum_HoshimachiSuiseiGachikoi, "Reach Gachikoi with Hoshimachi Suisei" },
	{ locationIndexEnum_SakuraMikoStageClear, "Clear a Stage with Sakura Miko" },
	{ locationIndexEnum_SakuraMikoGachikoi, "Reach Gachikoi with Sakura Miko" },
	{ locationIndexEnum_AkaiHaatoStageClear, "Clear a Stage with Akai Haato" },
	{ locationIndexEnum_AkaiHaatoGachikoi, "Reach Gachikoi with Akai Haato" },
	{ locationIndexEnum_YozoraMelStageClear, "Clear a Stage with Yozora Mel" },
	{ locationIndexEnum_YozoraMelGachikoi, "Reach Gachikoi with Yozora Mel" },
	{ locationIndexEnum_NatsuiroMatsuriStageClear, "Clear a Stage with Natsuiro Matsuri" },
	{ locationIndexEnum_NatsuiroMatsuriGachikoi, "Reach Gachikoi with Natsuiro Matsuri" },
	{ locationIndexEnum_AkiRosenthalStageClear, "Clear a Stage with Aki Rosenthal" },
	{ locationIndexEnum_AkiRosenthalGachikoi, "Reach Gachikoi with Aki Rosenthal" },
	{ locationIndexEnum_YuzukiChocoStageClear, "Clear a Stage with Yuzuki Choco" },
	{ locationIndexEnum_YuzukiChocoGachikoi, "Reach Gachikoi with Yuzuki Choco" },
	{ locationIndexEnum_OozoraSubaruStageClear, "Clear a Stage with Oozora Subaru" },
	{ locationIndexEnum_OozoraSubaruGachikoi, "Reach Gachikoi with Oozora Subaru" },
	{ locationIndexEnum_MurasakiShion10Minutes, "Reach 10 minutes with Murasaki Shion" },
	{ locationIndexEnum_MurasakiShionStageClear, "Clear a Stage with Murasaki Shion" },
	{ locationIndexEnum_MurasakiShionGachikoi, "Reach Gachikoi with Murasaki Shion" },
	{ locationIndexEnum_NakiriAyameStageClear, "Clear a Stage with Nakiri Ayame" },
	{ locationIndexEnum_NakiriAyameGachikoi, "Reach Gachikoi with Nakiri Ayame" },
	{ locationIndexEnum_MinatoAquaStageClear, "Clear a Stage with Minato Aqua" },
	{ locationIndexEnum_MinatoAquaGachikoi, "Reach Gachikoi with Minato Aqua" },
	{ locationIndexEnum_MoonaHoshinovaStageClear, "Clear a Stage with Moona Hoshinova" },
	{ locationIndexEnum_MoonaHoshinovaGachikoi, "Reach Gachikoi with Moona Hoshinova" },
	{ locationIndexEnum_AiraniIofifteenStageClear, "Clear a Stage with Airani Iofifteen" },
	{ locationIndexEnum_AiraniIofifteenGachikoi, "Reach Gachikoi with Airani Iofifteen" },
	{ locationIndexEnum_AyundaRisuStageClear, "Clear a Stage with Ayunda Risu" },
	{ locationIndexEnum_AyundaRisuGachikoi, "Reach Gachikoi with Ayunda Risu" },
	{ locationIndexEnum_KureijiOllieStageClear, "Clear a Stage with Kureiji Ollie" },
	{ locationIndexEnum_KureijiOllie10Minutes, "Reach 10 minutes with Kureiji Ollie" },
	{ locationIndexEnum_KureijiOllieGachikoi, "Reach Gachikoi with Kureiji Ollie" },
	{ locationIndexEnum_PavoliaReineStageClear, "Clear a Stage with Pavolia Reine" },
	{ locationIndexEnum_PavoliaReineGachikoi, "Reach Gachikoi with Pavolia Reine" },
	{ locationIndexEnum_AnyaMelfissaStageClear, "Clear a Stage with Anya Melfissa" },
	{ locationIndexEnum_AnyaMelfissaGachikoi, "Reach Gachikoi with Anya Melfissa" },
	{ locationIndexEnum_KoboKanaeruStageClear, "Clear a Stage with Kobo Kanaeru" },
	{ locationIndexEnum_KoboKanaeruGachikoi, "Reach Gachikoi with Kobo Kanaeru" },
	{ locationIndexEnum_KaelaKovalskiaStageClear, "Clear a Stage with Kaela Kovalskia" },
	{ locationIndexEnum_KaelaKovalskiaGachikoi, "Reach Gachikoi with Kaela Kovalskia" },
	{ locationIndexEnum_VestiaZeta10Minutes, "Reach 10 minutes with Vestia Zeta" },
	{ locationIndexEnum_VestiaZetaStageClear, "Clear a Stage with Vestia Zeta" },
	{ locationIndexEnum_VestiaZetaGachikoi, "Reach Gachikoi with Vestia Zeta" },
	{ locationIndexEnum_UsadaPekoraStageClear, "Clear a Stage with Usada Pekora" },
	{ locationIndexEnum_UsadaPekoraGachikoi, "Reach Gachikoi with Usada Pekora" },
	{ locationIndexEnum_ShiroganeNoelStageClear, "Clear a Stage with Shirogane Noel" },
	{ locationIndexEnum_ShiroganeNoelGachikoi, "Reach Gachikoi with Shirogane Noel" },
	{ locationIndexEnum_ShiranuiFlareStageClear, "Clear a Stage with Shiranui Flare" },
	{ locationIndexEnum_ShiranuiFlareGachikoi, "Reach Gachikoi with Shiranui Flare" },
	{ locationIndexEnum_HoushouMarineStageClear, "Clear a Stage with Houshou Marine" },
	{ locationIndexEnum_HoushouMarineGachikoi, "Reach Gachikoi with Houshou Marine" },
	{ locationIndexEnum_KiryuCocoStageClear, "Clear a Stage with Kiryu Coco" },
	{ locationIndexEnum_KiryuCocoGachikoi, "Reach Gachikoi with Kiryu Coco" },
	{ locationIndexEnum_AmaneKanataStageClear, "Clear a Stage with Amane Kanata" },
	{ locationIndexEnum_AmaneKanataGachikoi, "Reach Gachikoi with Amane Kanata" },
	{ locationIndexEnum_TsunomakiWatameStageClear, "Clear a Stage with Tsunomaki Watame" },
	{ locationIndexEnum_TsunomakiWatameGachikoi, "Reach Gachikoi with Tsunomaki Watame" },
	{ locationIndexEnum_TokoyamiTowaStageClear, "Clear a Stage with Tokoyami Towa" },
	{ locationIndexEnum_TokoyamiTowaGachikoi, "Reach Gachikoi with Tokoyami Towa" },
	{ locationIndexEnum_HimemoriLunaStageClear, "Clear a Stage with Himemori Luna" },
	{ locationIndexEnum_HimemoriLunaGachikoi, "Reach Gachikoi with Himemori Luna" },
	{ locationIndexEnum_FirstGame, "Complete your first game" },
	{ locationIndexEnum_DefeatFubura, "Defeat Fubura" },
	{ locationIndexEnum_DefeatStage1Boss, "Defeat the Boss of Stage 1" },
	{ locationIndexEnum_DefeatStage2Boss, "Defeat the Boss of Stage 2" },
	{ locationIndexEnum_DefeatStage3Boss, "Defeat the Boss of Stage 3" },
	{ locationIndexEnum_DefeatStage4Boss, "Defeat the Boss of Stage 4" },
	{ locationIndexEnum_DefeatStage5Boss, "Defeat the Boss of Stage 5" },
	{ locationIndexEnum_DefeatStage1HardBoss, "Defeat the Boss of Stage 1 (Hard)" },
	{ locationIndexEnum_DefeatStage2HardBoss, "Defeat the Boss of Stage 2 (Hard)" },
	{ locationIndexEnum_DefeatStage3HardBoss, "Defeat the Boss of Stage 3 (Hard)" },
	{ locationIndexEnum_DefeatStage4HardBoss, "Defeat the Boss of Stage 4 (Hard)" },
	{ locationIndexEnum_ClearTimeMode, "Clear a stage in Time Mode" },
	{ locationIndexEnum_UnlockAllCharacters, "Unlock all characters" },
	{ locationIndexEnum_UseSpecial, "Unlock and use a character's special" },
	{ locationIndexEnum_DestroyYagooStatue, "Destroy a Yagoo Statue" },
	{ locationIndexEnum_UseAnvil, "Use an anvil" },
	{ locationIndexEnum_CuttingBoard10Minutes, "Reach 10 minutes with Cutting Board or related weapons using certain characters" },
	{ locationIndexEnum_UsePlugTypeAsacoco, "Complete a stage using Plug-In Type Asacoco" },
	{ locationIndexEnum_5000Coins, "Have 5000 coins" },
	{ locationIndexEnum_1000000Coins, "Have 1,000,000 coins" },
	{ locationIndexEnum_UseSake, "Clear any stage while using Sake" },
	{ locationIndexEnum_Level50, "Reach level 50 in one game" },
	{ locationIndexEnum_Level100, "Reach level 100 in one game" },
	{ locationIndexEnum_Defeat5000, "Defeat at least 5000 targets in a stage" },
	{ locationIndexEnum_LoseWithHalu, "Be defeated while using Halu" },
	{ locationIndexEnum_Eat50Hamburgers, "Eat over 50 hamburgers in one game" },
	{ locationIndexEnum_Deal1000Damage, "Deal over 1000 damage in one attack" },
	{ locationIndexEnum_Deal10000Damage, "Deal over 10000 damage in one attack" },
	{ locationIndexEnum_NoMove, "Clear a game of Stage Mode without moving at all" },
	{ locationIndexEnum_10Minutes, "Lose after 10 minutes in a game" },
	{ locationIndexEnum_NoSpecial, "Clear a game of Stage Mode without using Special after unlocking it" },
	{ locationIndexEnum_UseSuperChattoTime, "Complete a stage while using Super Chatto Time" },
	{ locationIndexEnum_PetBubba, "Pet Bubba as Amelia Watson" },
	{ locationIndexEnum_Get4Collabs, "Get 4 Collab Weapons in 1 game" },
	{ locationIndexEnum_Take500Damage, "Take a total of over 500 damage in one game" },
	{ locationIndexEnum_EnhanceAWeapon, "Enhance a weapon once" },
	{ locationIndexEnum_DefeatYagoo, "Defeat a Yagoo" },
	{ locationIndexEnum_DefeatGoldYagoo, "Defeat a Golden Yagoo" },
	{ locationIndexEnum_DefeatSilverYagoo, "Defeat a Silver Yagoo" },
	{ locationIndexEnum_LoseToYagoo, "Be defeated by a Yagoo" },
	{ locationIndexEnum_SuperBox, "Open a Super Box" },
	{ locationIndexEnum_DropSuperItem, "Drop a super item" },
	{ locationIndexEnum_ClearHardcore, "Clear a stage in Hardcore Mode" },
	{ locationIndexEnum_10Enhance, "Get a weapon to +10 enhancements" },
	{ locationIndexEnum_MainWeaponOnly, "Clear with only your main weapon" },
	{ locationIndexEnum_Fail5Enhance, "Fail enhancements 5 times in 1 run" },
	{ locationIndexEnum_Fail1To2Enhance, "Fail a +1 > +2 enhancing" },
	{ locationIndexEnum_ClearHaluLevel5, "Clear with Halu level 5" },
	{ locationIndexEnum_30MinutesHaluLevel5, "Survive to 30 minutes with Halu level 5" },
	{ locationIndexEnum_DefeatBossUnder10Seconds, "Defeat a 10 or 20-minute boss in under 10 seconds" },
	{ locationIndexEnum_LeaveBossAlive5Minutes, "Leave a boss alive for 5 minutes or more" },
	{ locationIndexEnum_LevelUp5Times1Second, "Level up 5 times in a row in one second" },
	{ locationIndexEnum_CompleteArmory, "Complete the Armory" },
	{ locationIndexEnum_WatchCredits, "Watch the credits to the end" },
	{ locationIndexEnum_100Crit, "Get 100% crit chance in a single run" },
	{ locationIndexEnum_1MillionScore, "Achieve 1m+ score in a single run" },
	{ locationIndexEnum_WatchTV10Seconds, "Watch the TV for 10 seconds" },
	{ locationIndexEnum_NoDamage5Minutes, "Don't take any damage for 5 minutes" },
	{ locationIndexEnum_HoloHouse, "Go to Holo House" },
	{ locationIndexEnum_AnnoyMember, "Annoy another member" },
	{ locationIndexEnum_HarvestPlant, "Harvest a plant" },
	{ locationIndexEnum_CatchShinyFish, "Catch a Shiny fish" },
	{ locationIndexEnum_StealFish, "Steal a fish from another Holo member" },
	{ locationIndexEnum_CookDish, "Cook a dish" },
	{ locationIndexEnum_Fish10Combo, "Get 10 combos in the fishing minigame" },
	{ locationIndexEnum_Fish50Combo, "Get 50 combos in the fishing minigame" },
	{ locationIndexEnum_CatchEveryFish, "Catch at least one of every kind of fish" },
	{ locationIndexEnum_HarvestEveryCrop, "Harvest at least one of every kind of crop" },
	{ locationIndexEnum_MaxLevelWorker, "Level a worker to their maximum level" },
	{ locationIndexEnum_ManagerLevel4, "Get Manager Level 4" },
	{ locationIndexEnum_RetireWorker, "Retire a Worker" },
	{ locationIndexEnum_Collect10000CoinsWorkers, "Collect 100,000 HoloCoins from workers at once" },
	{ locationIndexEnum_Huh, "Huh?" },
	{ locationIndexEnum_NoItems, "Clear a stage with no items" },
	{ locationIndexEnum_GoldHammer, "Use the Golden Hammer" },
	{ locationIndexEnum_NoSkill, "Clear stage mode without having any Character Skills (Fandom off)" },
	{ locationIndexEnum_HasteUp10, "Choose the Haste Stat Up option 10 times when leveling up" },
	{ locationIndexEnum_IofiSpecial20Seconds, "Wait out the entire 20 seconds on Iofi's special without drawing anything" },
	{ locationIndexEnum_FirstOptionOnly, "Clear a stage only choosing the first option when leveling up without rerolls" },
	{ locationIndexEnum_HardNoProjectiles, "Clear a Hard Stage without taking any damage from projectiles" },
	{ locationIndexEnum_MainWeaponLevel1Only, "Clear a stage with Main Weapon at level 1 only" },
	{ locationIndexEnum_ClearHardNoHealItems, "Clear a (Hard) stage without taking any Healing Items" },
	{ locationIndexEnum_500HP, "Have over 500 HP in 1 run" },
	{ locationIndexEnum_UsadaCasino, "Enter the Usada Casino" },
	{ locationIndexEnum_WinWorkerRace, "Win a Worker Race" },
	{ locationIndexEnum_WinWorkerFight, "Win a Worker Fight" },
	{ locationIndexEnum_Get100000UsaChips, "Get 100,000 UsaChips" },
	{ locationIndexEnum_GetAPet, "Get a Pet in Holo House" },
	{ locationIndexEnum_LoseWith0UsaChips, "Lose in a Casino game with 0 UsaChips remaining" },
	{ locationIndexEnum_10FanLetters, "Find 10 Fan Letters" },
	{ locationIndexEnum_Stage4HardNoQuestionsWrong, "Get no questions wrong in Stage 4 (Hard)" },
	{ locationIndexEnum_WinJackpot, "Win a Jackpot in slots" },
	{ locationIndexEnum_Sell10Stamps, "Sell 10 Stamps in 1 run" },
	{ locationIndexEnum_500PickUpRange, "Reach 500% Pick Up Range" },
	{ locationIndexEnum_3DeathChickenFeather, "Clear a Stage Mode run after dying 3 times with Chickens Feather" },
	{ locationIndexEnum_ClearTowerOfSuffering, "Clear the Tower of Suffering" },
	{ locationIndexEnum_GetSomeHelp, "Complete all achievements. Then go outside" },
	{ locationIndexEnum_SpecialAttackShop, "Buy Special Attack Upgrade" },
	{ locationIndexEnum_GrowthShop1, "Buy Growth Upgrade 1 time" },
	{ locationIndexEnum_GrowthShop2, "Buy Growth Upgrade 2 times" },
	{ locationIndexEnum_GrowthShop3, "Buy Growth Upgrade 3 times" },
	{ locationIndexEnum_RerollShop1, "Buy Reroll Upgrade 1 time" },
	{ locationIndexEnum_RerollShop2, "Buy Reroll Upgrade 2 times" },
	{ locationIndexEnum_RerollShop3, "Buy Reroll Upgrade 3 times" },
	{ locationIndexEnum_RerollShop4, "Buy Reroll Upgrade 4 times" },
	{ locationIndexEnum_RerollShop5, "Buy Reroll Upgrade 5 times" },
	{ locationIndexEnum_RerollShop6, "Buy Reroll Upgrade 6 times" },
	{ locationIndexEnum_RerollShop7, "Buy Reroll Upgrade 7 times" },
	{ locationIndexEnum_RerollShop8, "Buy Reroll Upgrade 8 times" },
	{ locationIndexEnum_RerollShop9, "Buy Reroll Upgrade 9 times" },
	{ locationIndexEnum_RerollShop10, "Buy Reroll Upgrade 10 times" },
	{ locationIndexEnum_EliminateShop1, "Buy Eliminate Upgrade 1 time" },
	{ locationIndexEnum_EliminateShop2, "Buy Eliminate Upgrade 2 times" },
	{ locationIndexEnum_EliminateShop3, "Buy Eliminate Upgrade 3 times" },
	{ locationIndexEnum_EliminateShop4, "Buy Eliminate Upgrade 4 times" },
	{ locationIndexEnum_EliminateShop5, "Buy Eliminate Upgrade 5 times" },
	{ locationIndexEnum_EliminateShop6, "Buy Eliminate Upgrade 6 times" },
	{ locationIndexEnum_EliminateShop7, "Buy Eliminate Upgrade 7 times" },
	{ locationIndexEnum_EliminateShop8, "Buy Eliminate Upgrade 8 times" },
	{ locationIndexEnum_EliminateShop9, "Buy Eliminate Upgrade 9 times" },
	{ locationIndexEnum_EliminateShop10, "Buy Eliminate Upgrade 10 times" },
	{ locationIndexEnum_HoldShop1, "Buy Hold Upgrade 1 time" },
	{ locationIndexEnum_HoldShop2, "Buy Hold Upgrade 2 times" },
	{ locationIndexEnum_HoldShop3, "Buy Hold Upgrade 3 times" },
	{ locationIndexEnum_HoldShop4, "Buy Hold Upgrade 4 times" },
	{ locationIndexEnum_HoldShop5, "Buy Hold Upgrade 5 times" },
	{ locationIndexEnum_CustomizeShop, "Buy Customize Upgrade" },
	{ locationIndexEnum_SupportsShop, "Buy Support Upgrade" },
	{ locationIndexEnum_MaterialFindShop, "Buy Material Upgrade" },
	{ locationIndexEnum_StampsShop, "Buy Stamp Upgrade" },
	{ locationIndexEnum_EnchantShop, "Buy Enchant Upgrade" },
	{ locationIndexEnum_FandomShop, "Buy Fandom Upgrade" },
	{ locationIndexEnum_FanLetterShop, "Buy Fan Letter Upgrade" },
	{ locationIndexEnum_MaxHPShop1, "Buy Max HP Upgrade 1 time" },
	{ locationIndexEnum_MaxHPShop2, "Buy Max HP Upgrade 2 times" },
	{ locationIndexEnum_MaxHPShop3, "Buy Max HP Upgrade 3 times" },
	{ locationIndexEnum_MaxHPShop4, "Buy Max HP Upgrade 4 times" },
	{ locationIndexEnum_MaxHPShop5, "Buy Max HP Upgrade 5 times" },
	{ locationIndexEnum_MaxHPShop6, "Buy Max HP Upgrade 6 times" },
	{ locationIndexEnum_MaxHPShop7, "Buy Max HP Upgrade 7 times" },
	{ locationIndexEnum_MaxHPShop8, "Buy Max HP Upgrade 8 times" },
	{ locationIndexEnum_MaxHPShop9, "Buy Max HP Upgrade 9 times" },
	{ locationIndexEnum_MaxHPShop10, "Buy Max HP Upgrade 10 times" },
	{ locationIndexEnum_ATKShop1, "Buy ATK Upgrade 1 time" },
	{ locationIndexEnum_ATKShop2, "Buy ATK Upgrade 2 times" },
	{ locationIndexEnum_ATKShop3, "Buy ATK Upgrade 3 times" },
	{ locationIndexEnum_ATKShop4, "Buy ATK Upgrade 4 times" },
	{ locationIndexEnum_ATKShop5, "Buy ATK Upgrade 5 times" },
	{ locationIndexEnum_ATKShop6, "Buy ATK Upgrade 6 times" },
	{ locationIndexEnum_ATKShop7, "Buy ATK Upgrade 7 times" },
	{ locationIndexEnum_ATKShop8, "Buy ATK Upgrade 8 times" },
	{ locationIndexEnum_ATKShop9, "Buy ATK Upgrade 9 times" },
	{ locationIndexEnum_ATKShop10, "Buy ATK Upgrade 10 times" },
	{ locationIndexEnum_SPDShop1, "Buy SPD Upgrade 1 time" },
	{ locationIndexEnum_SPDShop2, "Buy SPD Upgrade 2 times" },
	{ locationIndexEnum_SPDShop3, "Buy SPD Upgrade 3 times" },
	{ locationIndexEnum_SPDShop4, "Buy SPD Upgrade 4 times" },
	{ locationIndexEnum_SPDShop5, "Buy SPD Upgrade 5 times" },
	{ locationIndexEnum_SPDShop6, "Buy SPD Upgrade 6 times" },
	{ locationIndexEnum_SPDShop7, "Buy SPD Upgrade 7 times" },
	{ locationIndexEnum_SPDShop8, "Buy SPD Upgrade 8 times" },
	{ locationIndexEnum_SPDShop9, "Buy SPD Upgrade 9 times" },
	{ locationIndexEnum_SPDShop10, "Buy SPD Upgrade 10 times" },
	{ locationIndexEnum_CritShop1, "Buy Crit Upgrade 1 time" },
	{ locationIndexEnum_CritShop2, "Buy Crit Upgrade 2 times" },
	{ locationIndexEnum_CritShop3, "Buy Crit Upgrade 3 times" },
	{ locationIndexEnum_CritShop4, "Buy Crit Upgrade 4 times" },
	{ locationIndexEnum_CritShop5, "Buy Crit Upgrade 5 times" },
	{ locationIndexEnum_PickUpRangeShop1, "Buy Pick Up Range Upgrade 1 time" },
	{ locationIndexEnum_PickUpRangeShop2, "Buy Pick Up Range Upgrade 2 times" },
	{ locationIndexEnum_PickUpRangeShop3, "Buy Pick Up Range Upgrade 3 times" },
	{ locationIndexEnum_PickUpRangeShop4, "Buy Pick Up Range Upgrade 4 times" },
	{ locationIndexEnum_PickUpRangeShop5, "Buy Pick Up Range Upgrade 5 times" },
	{ locationIndexEnum_PickUpRangeShop6, "Buy Pick Up Range Upgrade 6 times" },
	{ locationIndexEnum_PickUpRangeShop7, "Buy Pick Up Range Upgrade 7 times" },
	{ locationIndexEnum_PickUpRangeShop8, "Buy Pick Up Range Upgrade 8 times" },
	{ locationIndexEnum_PickUpRangeShop9, "Buy Pick Up Range Upgrade 9 times" },
	{ locationIndexEnum_PickUpRangeShop10, "Buy Pick Up Range Upgrade 10 times" },
	{ locationIndexEnum_HasteShop1, "Buy Haste Upgrade 1 time" },
	{ locationIndexEnum_HasteShop2, "Buy Haste Upgrade 2 times" },
	{ locationIndexEnum_HasteShop3, "Buy Haste Upgrade 3 times" },
	{ locationIndexEnum_HasteShop4, "Buy Haste Upgrade 4 times" },
	{ locationIndexEnum_HasteShop5, "Buy Haste Upgrade 5 times" },
	{ locationIndexEnum_RegenShop1, "Buy Regen Upgrade 1 time" },
	{ locationIndexEnum_RegenShop2, "Buy Regen Upgrade 2 times" },
	{ locationIndexEnum_RegenShop3, "Buy Regen Upgrade 3 times" },
	{ locationIndexEnum_RegenShop4, "Buy Regen Upgrade 4 times" },
	{ locationIndexEnum_RegenShop5, "Buy Regen Upgrade 5 times" },
	{ locationIndexEnum_DefenseShop1, "Buy Defense Upgrade 1 time" },
	{ locationIndexEnum_DefenseShop2, "Buy Defense Upgrade 2 times" },
	{ locationIndexEnum_DefenseShop3, "Buy Defense Upgrade 3 times" },
	{ locationIndexEnum_DefenseShop4, "Buy Defense Upgrade 4 times" },
	{ locationIndexEnum_DefenseShop5, "Buy Defense Upgrade 5 times" },
	{ locationIndexEnum_SpecialCDRShop1, "Buy Special Cooldown Reduction Upgrade 1 time" },
	{ locationIndexEnum_SpecialCDRShop2, "Buy Special Cooldown Reduction Upgrade 2 times" },
	{ locationIndexEnum_SpecialCDRShop3, "Buy Special Cooldown Reduction Upgrade 3 times" },
	{ locationIndexEnum_SpecialCDRShop4, "Buy Special Cooldown Reduction Upgrade 4 times" },
	{ locationIndexEnum_SpecialCDRShop5, "Buy Special Cooldown Reduction Upgrade 5 times" },
	{ locationIndexEnum_SkillUpShop1, "Buy Skill Up Upgrade 1 time" },
	{ locationIndexEnum_SkillUpShop2, "Buy Skill Up Upgrade 2 times" },
	{ locationIndexEnum_SkillUpShop3, "Buy Skill Up Upgrade 3 times" },
	{ locationIndexEnum_SkillUpShop4, "Buy Skill Up Upgrade 4 times" },
	{ locationIndexEnum_SkillUpShop5, "Buy Skill Up Upgrade 5 times" },
	{ locationIndexEnum_SkillUpShop6, "Buy Skill Up Upgrade 6 times" },
	{ locationIndexEnum_SkillUpShop7, "Buy Skill Up Upgrade 7 times" },
	{ locationIndexEnum_SkillUpShop8, "Buy Skill Up Upgrade 8 times" },
	{ locationIndexEnum_SkillUpShop9, "Buy Skill Up Upgrade 9 times" },
	{ locationIndexEnum_SkillUpShop10, "Buy Skill Up Upgrade 10 times" },
	{ locationIndexEnum_EXPGainShop1, "Buy EXP Gain Upgrade 1 time" },
	{ locationIndexEnum_EXPGainShop2, "Buy EXP Gain Upgrade 2 times" },
	{ locationIndexEnum_EXPGainShop3, "Buy EXP Gain Upgrade 3 times" },
	{ locationIndexEnum_EXPGainShop4, "Buy EXP Gain Upgrade 4 times" },
	{ locationIndexEnum_EXPGainShop5, "Buy EXP Gain Upgrade 5 times" },
	{ locationIndexEnum_FoodShop1, "Buy Food Upgrade 1 time" },
	{ locationIndexEnum_FoodShop2, "Buy Food Upgrade 2 times" },
	{ locationIndexEnum_FoodShop3, "Buy Food Upgrade 3 times" },
	{ locationIndexEnum_FoodShop4, "Buy Food Upgrade 4 times" },
	{ locationIndexEnum_FoodShop5, "Buy Food Upgrade 5 times" },
	{ locationIndexEnum_MoneyGainShop1, "Buy Money Gain Upgrade 1 time" },
	{ locationIndexEnum_MoneyGainShop2, "Buy Money Gain Upgrade 2 times" },
	{ locationIndexEnum_MoneyGainShop3, "Buy Money Gain Upgrade 3 times" },
	{ locationIndexEnum_MoneyGainShop4, "Buy Money Gain Upgrade 4 times" },
	{ locationIndexEnum_MoneyGainShop5, "Buy Money Gain Upgrade 5 times" },
	{ locationIndexEnum_MoneyGainShop6, "Buy Money Gain Upgrade 6 times" },
	{ locationIndexEnum_MoneyGainShop7, "Buy Money Gain Upgrade 7 times" },
	{ locationIndexEnum_MoneyGainShop8, "Buy Money Gain Upgrade 8 times" },
	{ locationIndexEnum_MoneyGainShop9, "Buy Money Gain Upgrade 9 times" },
	{ locationIndexEnum_MoneyGainShop10, "Buy Money Gain Upgrade 10 times" },
	{ locationIndexEnum_EnhancementShop1, "Buy Enhancement Upgrade 1 time" },
	{ locationIndexEnum_EnhancementShop2, "Buy Enhancement Upgrade 2 times" },
	{ locationIndexEnum_EnhancementShop3, "Buy Enhancement Upgrade 3 times" },
	{ locationIndexEnum_EnhancementShop4, "Buy Enhancement Upgrade 4 times" },
	{ locationIndexEnum_EnhancementShop5, "Buy Enhancement Upgrade 5 times" },
	{ locationIndexEnum_MarketingShop1, "Buy Marketing Upgrade 1 time" },
	{ locationIndexEnum_MarketingShop2, "Buy Marketing Upgrade 2 times" },
	{ locationIndexEnum_MarketingShop3, "Buy Marketing Upgrade 3 times" },
	{ locationIndexEnum_MarketingShop4, "Buy Marketing Upgrade 4 times" },
	{ locationIndexEnum_MarketingShop5, "Buy Marketing Upgrade 5 times" },
	{ locationIndexEnum_Obtain50Wheat, "Obtain 50 Wheat" },
	{ locationIndexEnum_Obtain50Tomato, "Obtain 50 Tomato" },
	{ locationIndexEnum_Obtain50Potato, "Obtain 50 Potato" },
	{ locationIndexEnum_Obtain50Rice, "Obtain 50 Rice" },
	{ locationIndexEnum_Obtain50Onion, "Obtain 50 Onion" },
	{ locationIndexEnum_Obtain50Carrot, "Obtain 50 Carrot" },
	{ locationIndexEnum_Obtain50GreenBean, "Obtain 50 Green Bean" },
	{ locationIndexEnum_Obtain50Pepper, "Obtain 50 Pepper" },
	{ locationIndexEnum_Obtain50Strawberry, "Obtain 50 Strawberry" },
	{ locationIndexEnum_Obtain50Corn, "Obtain 50 Corn" },
	{ locationIndexEnum_Obtain50Radish, "Obtain 50 Radish" },
	{ locationIndexEnum_Obtain50Garlic, "Obtain 50 Garlic" },
	{ locationIndexEnum_Obtain50Shrimp, "Obtain 50 Shrimp" },
	{ locationIndexEnum_Obtain50Salmon, "Obtain 50 Salmon" },
	{ locationIndexEnum_Obtain50Tuna, "Obtain 50 Tuna" },
	{ locationIndexEnum_Obtain50KoiFish, "Obtain 50 Koi Fish" },
	{ locationIndexEnum_Obtain50Lobster, "Obtain 50 Lobster" },
	{ locationIndexEnum_Obtain50Eel, "Obtain 50 Eel" },
	{ locationIndexEnum_Obtain50Pufferfish, "Obtain 50 Pufferfish" },
	{ locationIndexEnum_Obtain50MantaRay, "Obtain 50 Manta Ray" },
	{ locationIndexEnum_Obtain50Turtle, "Obtain 50 Turtle" },
	{ locationIndexEnum_Obtain50Squid, "Obtain 50 Squid" },
	{ locationIndexEnum_Obtain50Shark, "Obtain 50 Shark" },
	{ locationIndexEnum_Obtain50Axolotl, "Obtain 50 Axolotl" },
	{ locationIndexEnum_Cook10Tempura, "Cook 10 Tempura" },
	{ locationIndexEnum_Cook10TunaSandwich, "Cook 10 Tuna Sandwich" },
	{ locationIndexEnum_Cook10SushiSet, "Cook 10 Sushi Set" },
	{ locationIndexEnum_Cook10PokeBowl, "Cook 10 Poke Bowl" },
	{ locationIndexEnum_Cook10LobsterDinner, "Cook 10 Lobster Dinner" },
	{ locationIndexEnum_Cook10PufferfishMealSet, "Cook 10 Pufferfish Meal Set" },
	{ locationIndexEnum_Cook10VegatarianBurgerAndFries, "Cook 10 Vegatarian Burger and Fries" },
	{ locationIndexEnum_Cook10TurtleSoup, "Cook 10 Turtle Soup" },
	{ locationIndexEnum_Cook10UnagiDon, "Cook 10 Unagi Don" },
	{ locationIndexEnum_Cook10CalamariSet, "Cook 10 Calamari Set" },
	{ locationIndexEnum_Cook10MantaRaySet, "Cook 10 Manta Ray Set" },
	{ locationIndexEnum_Cook10FruitSandwich, "Cook 10 Fruit Sandwich" },
	{ locationIndexEnum_Cook10BurgerMeal, "Cook 10 Burger Meal" },
	{ locationIndexEnum_Cook10StrangeSeafoodSoup, "Cook 10 Strange Seafood Soup" },
	{ locationIndexEnum_Cook10VegetableSoup, "Cook 10 Vegetable Soup" },
	{ locationIndexEnum_Cook10BBQSquid, "Cook 10 BBQ Squid" },
	{ locationIndexEnum_Cook10SpicySeafoodUdon, "Cook 10 Spicy Seafood Udon" },
	{ locationIndexEnum_MakeStoneAxe, "Make a Stone Axe" },
	{ locationIndexEnum_MakeLeadAxe, "Make a Lead Axe" },
	{ locationIndexEnum_MakeIronAxe, "Make an Iron Axe" },
	{ locationIndexEnum_MakeMythAxe, "Make a Myth Axe" },
	{ locationIndexEnum_MakePromiseAxe, "Make a Promise Axe" },
	{ locationIndexEnum_MakeAdventAxe, "Make an Advent Axe" },
	{ locationIndexEnum_MakeJusticeAxe, "Make a Justice Axe" },
	{ locationIndexEnum_MakeHololiteAxe, "Make a Hololite Axe" },
	{ locationIndexEnum_MakeStonePickaxe, "Make a Stone Pickaxe" },
	{ locationIndexEnum_MakeLeadPickaxe, "Make a Lead Pickaxe" },
	{ locationIndexEnum_MakeIronPickaxe, "Make an Iron Pickaxe" },
	{ locationIndexEnum_MakeMythPickaxe, "Make a Myth Pickaxe" },
	{ locationIndexEnum_MakePromisePickaxe, "Make a Promise Pickaxe" },
	{ locationIndexEnum_MakeAdventPickaxe, "Make an Advent Pickaxe" },
	{ locationIndexEnum_MakeJusticePickaxe, "Make a Justice Pickaxe" },
	{ locationIndexEnum_MakeHololitePickaxe, "Make a Hololite Pickaxe" },
	{ locationIndexEnum_MakeBasicPrism, "Make a Basic Prism" },
	{ locationIndexEnum_MakeMythPrism, "Make a Myth Prism" },
	{ locationIndexEnum_MakePromisePrism, "Make a Promise Prism" },
	{ locationIndexEnum_MakeAdventPrism, "Make an Advent Prism" },
	{ locationIndexEnum_MakeJusticePrism, "Make a Justice Prism" },
	{ locationIndexEnum_MakeHololitePrism, "Make a Hololite Prism" },
	{ locationIndexEnum_ReachWoodcuttingLevel2, "Reach Woodcutting Level 2" },
	{ locationIndexEnum_ReachWoodcuttingLevel3, "Reach Woodcutting Level 3" },
	{ locationIndexEnum_ReachWoodcuttingLevel4, "Reach Woodcutting Level 4" },
	{ locationIndexEnum_ReachWoodcuttingLevel5, "Reach Woodcutting Level 5" },
	{ locationIndexEnum_ReachWoodcuttingLevel6, "Reach Woodcutting Level 6" },
	{ locationIndexEnum_ReachWoodcuttingLevel7, "Reach Woodcutting Level 7" },
	{ locationIndexEnum_ReachWoodcuttingLevel8, "Reach Woodcutting Level 8" },
	{ locationIndexEnum_ReachWoodcuttingLevel9, "Reach Woodcutting Level 9" },
	{ locationIndexEnum_ReachMiningLevel2, "Reach Mining Level 2" },
	{ locationIndexEnum_ReachMiningLevel3, "Reach Mining Level 3" },
	{ locationIndexEnum_ReachMiningLevel4, "Reach Mining Level 4" },
	{ locationIndexEnum_ReachMiningLevel5, "Reach Mining Level 5" },
	{ locationIndexEnum_ReachMiningLevel6, "Reach Mining Level 6" },
	{ locationIndexEnum_ReachMiningLevel7, "Reach Mining Level 7" },
	{ locationIndexEnum_ReachMiningLevel8, "Reach Mining Level 8" },
	{ locationIndexEnum_ReachMiningLevel9, "Reach Mining Level 9" },
	{ locationIndexEnum_Defeat1Chumbud, "Defeat 1 Chumbud" },
	{ locationIndexEnum_Defeat1ChumbudQ, "Defeat 1 Chumbud (Q)" },
	{ locationIndexEnum_Defeat1Deadbeat, "Defeat 1 Deadbeat" },
	{ locationIndexEnum_Defeat1DeadbeatQ, "Defeat 1 Deadbeat (Q)" },
	{ locationIndexEnum_Defeat1Takodachi, "Defeat 1 Takodachi" },
	{ locationIndexEnum_Defeat1KFP, "Defeat 1 KFP" },
	{ locationIndexEnum_Defeat1Teamate, "Defeat 1 Tea-mate" },
	{ locationIndexEnum_Defeat1CursedBubba, "Defeat 1 Cursed Bubba" },
	{ locationIndexEnum_Defeat1SmolAme, "Defeat 1 Smol Ame" },
	{ locationIndexEnum_Defeat1Brat, "Defeat 1 Brat" },
	{ locationIndexEnum_Defeat1BaeHalloween, "Defeat 1 Bae (Halloween)" },
	{ locationIndexEnum_Defeat1Hooman, "Defeat 1 Hooman" },
	{ locationIndexEnum_Defeat1Sapling, "Defeat 1 Sapling" },
	{ locationIndexEnum_Defeat1Kronie, "Defeat 1 Kronie" },
	{ locationIndexEnum_Defeat1Sanalite, "Defeat 1 Sanalite" },
	{ locationIndexEnum_Defeat1Yatagarasu, "Defeat 1 Yatagarasu" },
	{ locationIndexEnum_Defeat1GuyRys, "Defeat 1 GuyRys" },
	{ locationIndexEnum_Defeat1IrystocratLegacy, "Defeat 1 Irystocrat (Legacy)" },
	{ locationIndexEnum_Defeat1BloomAndGloom, "Defeat 1 Bloom & Gloom" },
	{ locationIndexEnum_Defeat1Sukonbu, "Defeat 1 Sukonbu" },
	{ locationIndexEnum_Defeat1FubuChun, "Defeat 1 Fubu-chun" },
	{ locationIndexEnum_Defeat1Oruyanke, "Defeat 1 Oruyanke" },
	{ locationIndexEnum_Defeat1Miteiru, "Defeat 1 Miteiru" },
	{ locationIndexEnum_Defeat1Fubura, "Defeat 1 Fubura" },
	{ locationIndexEnum_Defeat1Miofa, "Defeat 1 Miofa" },
	{ locationIndexEnum_Defeat1Koronesuki, "Defeat 1 Koronesuki" },
	{ locationIndexEnum_Defeat1Onigiriya, "Defeat 1 Onigiriya" },
	{ locationIndexEnum_Defeat135P, "Defeat 1 35P" },
	{ locationIndexEnum_Defeat1Kintoki, "Defeat 1 Kintoki" },
	{ locationIndexEnum_Defeat1Mikodanye, "Defeat 1 Mikodanye" },
	{ locationIndexEnum_Defeat1Soratomo, "Defeat 1 Soratomo" },
	{ locationIndexEnum_Defeat1Pioneer, "Defeat 1 Pioneer" },
	{ locationIndexEnum_Defeat1Hoshiyomi, "Defeat 1 Hoshiyomi" },
	{ locationIndexEnum_Defeat1Robosa, "Defeat 1 Robosa" },
	{ locationIndexEnum_Defeat1SSRB, "Defeat 1 SSRB" },
	{ locationIndexEnum_Defeat1Staff, "Defeat 1 Staff" },
	{ locationIndexEnum_Defeat1AChan, "Defeat 1 A-chan" },
	{ locationIndexEnum_Defeat1HarusakiNodoka, "Defeat 1 Harusaki Nodoka" },
	{ locationIndexEnum_Defeat1Matsurisu, "Defeat 1 Matsurisu" },
	{ locationIndexEnum_Defeat1Haaton, "Defeat 1 Haaton" },
	{ locationIndexEnum_Defeat1Kapumin, "Defeat 1 Kapumin" },
	{ locationIndexEnum_Defeat1ObakeChan, "Defeat 1 Obake-Chan" },
	{ locationIndexEnum_Defeat1Rosetai, "Defeat 1 Rosetai" },
	{ locationIndexEnum_Defeat1Subatomo, "Defeat 1 Subatomo" },
	{ locationIndexEnum_Defeat1Shubangelion, "Defeat 1 Shubangelion" },
	{ locationIndexEnum_Defeat1Chocomate, "Defeat 1 Chocomate" },
	{ locationIndexEnum_Defeat1Chocolat, "Defeat 1 Chocolat" },
	{ locationIndexEnum_Defeat1Aquacrew, "Defeat 1 Aquacrew" },
	{ locationIndexEnum_Defeat1Shiokko, "Defeat 1 Shiokko" },
	{ locationIndexEnum_Defeat1Nakirigumi, "Defeat 1 Nakirigumi" },
	{ locationIndexEnum_Defeat1Poyoyo, "Defeat 1 Poyoyo" },
	{ locationIndexEnum_Defeat1Spiderchama, "Defeat 1 Spiderchama" },
	{ locationIndexEnum_Defeat1HalloweenMyth, "Defeat 1 Halloween Myth" },
	{ locationIndexEnum_Defeat1Moonafic, "Defeat 1 Moonafic" },
	{ locationIndexEnum_Defeat1Moonabito, "Defeat 1 Moonabito" },
	{ locationIndexEnum_Defeat1Risuner, "Defeat 1 Risuner" },
	{ locationIndexEnum_Defeat1Riscot, "Defeat 1 Riscot" },
	{ locationIndexEnum_Defeat1Ioforia, "Defeat 1 Ioforia" },
	{ locationIndexEnum_Defeat1Zomrade, "Defeat 1 Zomrade" },
	{ locationIndexEnum_Defeat1Udin, "Defeat 1 Udin" },
	{ locationIndexEnum_Defeat1Merakyat, "Defeat 1 Merakyat" },
	{ locationIndexEnum_Defeat1Melfriend, "Defeat 1 Melfriend" },
	{ locationIndexEnum_Defeat1Kobokerz, "Defeat 1 Kobokerz" },
	{ locationIndexEnum_Defeat1Cilus, "Defeat 1 Cilus" },
	{ locationIndexEnum_Defeat1Zecretary, "Defeat 1 Zecretary" },
	{ locationIndexEnum_Defeat1Bazo, "Defeat 1 Bazo" },
	{ locationIndexEnum_Defeat1Pemaloe, "Defeat 1 Pemaloe" },
	{ locationIndexEnum_Defeat1Area15, "Defeat 1 Area 15" },
	{ locationIndexEnum_Defeat1Nousagi, "Defeat 1 Nousagi" },
	{ locationIndexEnum_Defeat1HoushouNoIchimin, "Defeat 1 Houshou no Ichimin" },
	{ locationIndexEnum_Defeat1Elfriend, "Defeat 1 Elfriend" },
	{ locationIndexEnum_Defeat1KnightsOrderOfShirogane, "Defeat 1 Knight's Order of Shirogane" },
	{ locationIndexEnum_Defeat1Tatsunoko, "Defeat 1 Tatsunoko" },
	{ locationIndexEnum_Defeat1Heimin, "Defeat 1 Heimin" },
	{ locationIndexEnum_Defeat1Upao, "Defeat 1 Upao" },
	{ locationIndexEnum_Defeat1Watamate, "Defeat 1 Watamate" },
	{ locationIndexEnum_Defeat1TokoyamiKenzoku, "Defeat 1 Tokoyami Kenzoku" },
	{ locationIndexEnum_Defeat1LuKnight, "Defeat 1 LuKnight" },
	{ locationIndexEnum_Defeat1Nanoraaa, "Defeat 1 Nanoraaa" },
	{ locationIndexEnum_Defeat1Pekodam, "Defeat 1 Pekodam" },
	{ locationIndexEnum_Defeat1GoriEla, "Defeat 1 GoriEla" },
	{ locationIndexEnum_Defeat1Otaku, "Defeat 1 Otaku" },
};

std::unordered_map<itemIndexEnum, locationIndexEnum> shopItemToLocationMap
{
	{ itemIndexEnum_SpecialAttackShopUpgrade, locationIndexEnum_SpecialAttackShop },
	{ itemIndexEnum_GrowthProgressiveShopUpgrade, locationIndexEnum_GrowthShop1 },
	{ itemIndexEnum_RerollProgressiveShopUpgrade, locationIndexEnum_RerollShop1 },
	{ itemIndexEnum_EliminateProgressiveShopUpgrade, locationIndexEnum_EliminateShop1 },
	{ itemIndexEnum_HoldProgressiveShopUpgrade, locationIndexEnum_HoldShop1 },
	{ itemIndexEnum_CustomizeShopUpgrade, locationIndexEnum_CustomizeShop },
	{ itemIndexEnum_SupportsShopUpgrade, locationIndexEnum_SupportsShop },
	{ itemIndexEnum_MaterialShopUpgrade, locationIndexEnum_MaterialFindShop },
	{ itemIndexEnum_StampsShopUpgrade, locationIndexEnum_StampsShop },
	{ itemIndexEnum_EnchantmentsShopUpgrade, locationIndexEnum_EnchantShop },
	{ itemIndexEnum_FandomShopUpgrade, locationIndexEnum_FandomShop },
	{ itemIndexEnum_FanLettersShopUpgrade, locationIndexEnum_FanLetterShop },
	{ itemIndexEnum_MaxHPProgressiveShopUpgrade, locationIndexEnum_MaxHPShop1 },
	{ itemIndexEnum_ATKProgressiveShopUpgrade, locationIndexEnum_ATKShop1 },
	{ itemIndexEnum_SPDProgressiveShopUpgrade, locationIndexEnum_SPDShop1 },
	{ itemIndexEnum_CritProgressiveShopUpgrade, locationIndexEnum_CritShop1 },
	{ itemIndexEnum_PickUpProgressiveShopUpgrade, locationIndexEnum_PickUpRangeShop1 },
	{ itemIndexEnum_HasteProgressiveShopUpgrade, locationIndexEnum_HasteShop1 },
	{ itemIndexEnum_RegenProgressiveShopUpgrade, locationIndexEnum_RegenShop1 },
	{ itemIndexEnum_DefenseProgressiveShopUpgrade, locationIndexEnum_DefenseShop1 },
	{ itemIndexEnum_SpecialCooldownProgressiveShopUpgrade, locationIndexEnum_SpecialCDRShop1 },
	{ itemIndexEnum_SkillUpProgressiveShopUpgrade, locationIndexEnum_SkillUpShop1 },
	{ itemIndexEnum_EXPGainProgressiveShopUpgrade, locationIndexEnum_EXPGainShop1 },
	{ itemIndexEnum_FoodDropProgressiveShopUpgrade, locationIndexEnum_FoodShop1 },
	{ itemIndexEnum_MoneyGainProgressiveShopUpgrade, locationIndexEnum_MoneyGainShop1 },
	{ itemIndexEnum_EnhancementProgressiveShopUpgrade, locationIndexEnum_EnhancementShop1 },
	{ itemIndexEnum_MarketingProgressiveShopUpgrade, locationIndexEnum_MarketingShop1 },
};

std::unordered_set<locationIndexEnum> holoHouseRandomizationLocations
{
	locationIndexEnum_HoloHouse,
	locationIndexEnum_AnnoyMember,
	locationIndexEnum_HarvestPlant,
	locationIndexEnum_CatchShinyFish,
	locationIndexEnum_StealFish,
	locationIndexEnum_CookDish,
	locationIndexEnum_Fish10Combo,
	locationIndexEnum_Fish50Combo,
	locationIndexEnum_CatchEveryFish,
	locationIndexEnum_HarvestEveryCrop,
	locationIndexEnum_MaxLevelWorker,
	locationIndexEnum_ManagerLevel4,
	locationIndexEnum_RetireWorker,
	locationIndexEnum_Collect10000CoinsWorkers,
	locationIndexEnum_Huh,
	locationIndexEnum_UsadaCasino,
	locationIndexEnum_WinWorkerRace,
	locationIndexEnum_WinWorkerFight,
	locationIndexEnum_Get100000UsaChips,
	locationIndexEnum_GetAPet,
	locationIndexEnum_LoseWith0UsaChips,
	locationIndexEnum_WinJackpot,
	locationIndexEnum_ClearTowerOfSuffering,
	locationIndexEnum_Obtain50Wheat,
	locationIndexEnum_Obtain50Tomato,
	locationIndexEnum_Obtain50Potato,
	locationIndexEnum_Obtain50Rice,
	locationIndexEnum_Obtain50Onion,
	locationIndexEnum_Obtain50Carrot,
	locationIndexEnum_Obtain50GreenBean,
	locationIndexEnum_Obtain50Pepper,
	locationIndexEnum_Obtain50Strawberry,
	locationIndexEnum_Obtain50Corn,
	locationIndexEnum_Obtain50Radish,
	locationIndexEnum_Obtain50Garlic,
	locationIndexEnum_Obtain50Shrimp,
	locationIndexEnum_Obtain50Salmon,
	locationIndexEnum_Obtain50Tuna,
	locationIndexEnum_Obtain50KoiFish,
	locationIndexEnum_Obtain50Lobster,
	locationIndexEnum_Obtain50Eel,
	locationIndexEnum_Obtain50Pufferfish,
	locationIndexEnum_Obtain50MantaRay,
	locationIndexEnum_Obtain50Turtle,
	locationIndexEnum_Obtain50Squid,
	locationIndexEnum_Obtain50Shark,
	locationIndexEnum_Obtain50Axolotl,
	locationIndexEnum_Cook10Tempura,
	locationIndexEnum_Cook10TunaSandwich,
	locationIndexEnum_Cook10SushiSet,
	locationIndexEnum_Cook10PokeBowl,
	locationIndexEnum_Cook10LobsterDinner,
	locationIndexEnum_Cook10PufferfishMealSet,
	locationIndexEnum_Cook10VegatarianBurgerAndFries,
	locationIndexEnum_Cook10TurtleSoup,
	locationIndexEnum_Cook10UnagiDon,
	locationIndexEnum_Cook10CalamariSet,
	locationIndexEnum_Cook10MantaRaySet,
	locationIndexEnum_Cook10FruitSandwich,
	locationIndexEnum_Cook10BurgerMeal,
	locationIndexEnum_Cook10StrangeSeafoodSoup,
	locationIndexEnum_Cook10VegetableSoup,
	locationIndexEnum_Cook10BBQSquid,
	locationIndexEnum_Cook10SpicySeafoodUdon,
	locationIndexEnum_MakeStoneAxe,
	locationIndexEnum_MakeLeadAxe,
	locationIndexEnum_MakeIronAxe,
	locationIndexEnum_MakeMythAxe,
	locationIndexEnum_MakePromiseAxe,
	locationIndexEnum_MakeAdventAxe,
	locationIndexEnum_MakeJusticeAxe,
	locationIndexEnum_MakeHololiteAxe,
	locationIndexEnum_MakeStonePickaxe,
	locationIndexEnum_MakeLeadPickaxe,
	locationIndexEnum_MakeIronPickaxe,
	locationIndexEnum_MakeMythPickaxe,
	locationIndexEnum_MakePromisePickaxe,
	locationIndexEnum_MakeAdventPickaxe,
	locationIndexEnum_MakeJusticePickaxe,
	locationIndexEnum_MakeHololitePickaxe,
	locationIndexEnum_MakeBasicPrism,
	locationIndexEnum_MakeMythPrism,
	locationIndexEnum_MakePromisePrism,
	locationIndexEnum_MakeAdventPrism,
	locationIndexEnum_MakeJusticePrism,
	locationIndexEnum_MakeHololitePrism,
	locationIndexEnum_ReachWoodcuttingLevel2,
	locationIndexEnum_ReachWoodcuttingLevel3,
	locationIndexEnum_ReachWoodcuttingLevel4,
	locationIndexEnum_ReachWoodcuttingLevel5,
	locationIndexEnum_ReachWoodcuttingLevel6,
	locationIndexEnum_ReachWoodcuttingLevel7,
	locationIndexEnum_ReachWoodcuttingLevel8,
	locationIndexEnum_ReachWoodcuttingLevel9,
	locationIndexEnum_ReachMiningLevel2,
	locationIndexEnum_ReachMiningLevel3,
	locationIndexEnum_ReachMiningLevel4,
	locationIndexEnum_ReachMiningLevel5,
	locationIndexEnum_ReachMiningLevel6,
	locationIndexEnum_ReachMiningLevel7,
	locationIndexEnum_ReachMiningLevel8,
	locationIndexEnum_ReachMiningLevel9,
};

std::unordered_map<std::string, locationIndexEnum> itemNameToLocationMap
{
	{ "wheat", locationIndexEnum_Obtain50Wheat },
	{ "tomato", locationIndexEnum_Obtain50Tomato },
	{ "potato", locationIndexEnum_Obtain50Potato },
	{ "rice", locationIndexEnum_Obtain50Rice },
	{ "onion", locationIndexEnum_Obtain50Onion },
	{ "carrot", locationIndexEnum_Obtain50Carrot },
	{ "greenbeans", locationIndexEnum_Obtain50GreenBean },
	{ "peppers", locationIndexEnum_Obtain50Pepper },
	{ "strawberry", locationIndexEnum_Obtain50Strawberry },
	{ "corn", locationIndexEnum_Obtain50Corn },
	{ "radish", locationIndexEnum_Obtain50Radish },
	{ "garlic", locationIndexEnum_Obtain50Garlic },
	{ "shrimp", locationIndexEnum_Obtain50Shrimp },
	{ "clownfish", locationIndexEnum_Obtain50Salmon },
	{ "tuna", locationIndexEnum_Obtain50Tuna },
	{ "koifish", locationIndexEnum_Obtain50KoiFish },
	{ "lobster", locationIndexEnum_Obtain50Lobster },
	{ "pufferfish", locationIndexEnum_Obtain50Pufferfish },
	{ "mantaray", locationIndexEnum_Obtain50MantaRay },
	{ "turtle", locationIndexEnum_Obtain50Turtle },
	{ "squid", locationIndexEnum_Obtain50Squid },
	{ "shark", locationIndexEnum_Obtain50Shark },
	{ "axolotl", locationIndexEnum_Obtain50Axolotl },
	{ "tempura", locationIndexEnum_Cook10Tempura },
	{ "tunasandwich", locationIndexEnum_Cook10TunaSandwich },
	{ "sushiset", locationIndexEnum_Cook10SushiSet },
	{ "pokebowl", locationIndexEnum_Cook10PokeBowl },
	{ "lobsterdinner", locationIndexEnum_Cook10LobsterDinner },
	{ "pufferfishmeal", locationIndexEnum_Cook10PufferfishMealSet },
	{ "vegetarianburger", locationIndexEnum_Cook10VegatarianBurgerAndFries },
	{ "turtlesoup", locationIndexEnum_Cook10TurtleSoup },
	{ "unagidon", locationIndexEnum_Cook10UnagiDon },
	{ "calamariset", locationIndexEnum_Cook10CalamariSet },
	{ "mantaraysoup", locationIndexEnum_Cook10MantaRaySet },
	{ "fruitsandwich", locationIndexEnum_Cook10FruitSandwich },
	{ "burgermeal", locationIndexEnum_Cook10BurgerMeal },
	{ "strangeseafoodsoup", locationIndexEnum_Cook10StrangeSeafoodSoup },
	{ "vegetablesoup", locationIndexEnum_Cook10VegetableSoup },
	{ "bbqsquid", locationIndexEnum_Cook10BBQSquid },
	{ "spicyudon", locationIndexEnum_Cook10SpicySeafoodUdon },
};

std::unordered_map<itemIndexEnum, std::string> holoHouseItemToIDMap
{
	{ itemIndexEnum_StandardSoil, "standardsoil" },
	{ itemIndexEnum_ExpeditedSoil, "expeditedsoil" },
	{ itemIndexEnum_EnhancedSoil, "enhancedsoil" },
	{ itemIndexEnum_WheatSeed, "wheatSeed" },
	{ itemIndexEnum_TomatoSeed, "tomatoSeed" },
	{ itemIndexEnum_PotatoSeed, "potatoSeed" },
	{ itemIndexEnum_RiceSeed, "riceSeed" },
	{ itemIndexEnum_OnionSeed, "onionseed" },
	{ itemIndexEnum_CarrotSeed, "carrotseed" },
	{ itemIndexEnum_GreenBeanSeed, "greenbeansseed" },
	{ itemIndexEnum_PepperSeed, "peppersseed" },
	{ itemIndexEnum_StrawberrySeed, "strawberryseed" },
	{ itemIndexEnum_CornSeed, "cornseed" },
	{ itemIndexEnum_RadishSeed, "radishseed" },
	{ itemIndexEnum_GarlicSeed, "garlicseed" },
};

std::unordered_set<locationIndexEnum> enemyCheckLocations
{
	locationIndexEnum_Defeat1Chumbud,
	locationIndexEnum_Defeat1ChumbudQ,
	locationIndexEnum_Defeat1Deadbeat,
	locationIndexEnum_Defeat1DeadbeatQ,
	locationIndexEnum_Defeat1Takodachi,
	locationIndexEnum_Defeat1KFP,
	locationIndexEnum_Defeat1Teamate,
	locationIndexEnum_Defeat1CursedBubba,
	locationIndexEnum_Defeat1SmolAme,
	locationIndexEnum_Defeat1Brat,
	locationIndexEnum_Defeat1BaeHalloween,
	locationIndexEnum_Defeat1Hooman,
	locationIndexEnum_Defeat1Sapling,
	locationIndexEnum_Defeat1Kronie,
	locationIndexEnum_Defeat1Sanalite,
	locationIndexEnum_Defeat1Yatagarasu,
	locationIndexEnum_Defeat1GuyRys,
	locationIndexEnum_Defeat1IrystocratLegacy,
	locationIndexEnum_Defeat1BloomAndGloom,
	locationIndexEnum_Defeat1Sukonbu,
	locationIndexEnum_Defeat1FubuChun,
	locationIndexEnum_Defeat1Oruyanke,
	locationIndexEnum_Defeat1Miteiru,
	locationIndexEnum_Defeat1Fubura,
	locationIndexEnum_Defeat1Miofa,
	locationIndexEnum_Defeat1Koronesuki,
	locationIndexEnum_Defeat1Onigiriya,
	locationIndexEnum_Defeat135P,
	locationIndexEnum_Defeat1Kintoki,
	locationIndexEnum_Defeat1Mikodanye,
	locationIndexEnum_Defeat1Soratomo,
	locationIndexEnum_Defeat1Pioneer,
	locationIndexEnum_Defeat1Hoshiyomi,
	locationIndexEnum_Defeat1Robosa,
	locationIndexEnum_Defeat1SSRB,
	locationIndexEnum_Defeat1Staff,
	locationIndexEnum_Defeat1AChan,
	locationIndexEnum_Defeat1HarusakiNodoka,
	locationIndexEnum_Defeat1Matsurisu,
	locationIndexEnum_Defeat1Haaton,
	locationIndexEnum_Defeat1Kapumin,
	locationIndexEnum_Defeat1ObakeChan,
	locationIndexEnum_Defeat1Rosetai,
	locationIndexEnum_Defeat1Subatomo,
	locationIndexEnum_Defeat1Shubangelion,
	locationIndexEnum_Defeat1Chocomate,
	locationIndexEnum_Defeat1Chocolat,
	locationIndexEnum_Defeat1Aquacrew,
	locationIndexEnum_Defeat1Shiokko,
	locationIndexEnum_Defeat1Nakirigumi,
	locationIndexEnum_Defeat1Poyoyo,
	locationIndexEnum_Defeat1Spiderchama,
	locationIndexEnum_Defeat1HalloweenMyth,
	locationIndexEnum_Defeat1Moonafic,
	locationIndexEnum_Defeat1Moonabito,
	locationIndexEnum_Defeat1Risuner,
	locationIndexEnum_Defeat1Riscot,
	locationIndexEnum_Defeat1Ioforia,
	locationIndexEnum_Defeat1Zomrade,
	locationIndexEnum_Defeat1Udin,
	locationIndexEnum_Defeat1Merakyat,
	locationIndexEnum_Defeat1Melfriend,
	locationIndexEnum_Defeat1Kobokerz,
	locationIndexEnum_Defeat1Cilus,
	locationIndexEnum_Defeat1Zecretary,
	locationIndexEnum_Defeat1Bazo,
	locationIndexEnum_Defeat1Pemaloe,
	locationIndexEnum_Defeat1Area15,
	locationIndexEnum_Defeat1Nousagi,
	locationIndexEnum_Defeat1HoushouNoIchimin,
	locationIndexEnum_Defeat1Elfriend,
	locationIndexEnum_Defeat1KnightsOrderOfShirogane,
	locationIndexEnum_Defeat1Tatsunoko,
	locationIndexEnum_Defeat1Heimin,
	locationIndexEnum_Defeat1Upao,
	locationIndexEnum_Defeat1Watamate,
	locationIndexEnum_Defeat1TokoyamiKenzoku,
	locationIndexEnum_Defeat1LuKnight,
	locationIndexEnum_Defeat1Nanoraaa,
	locationIndexEnum_Defeat1Pekodam,
	locationIndexEnum_Defeat1GoriEla,
	locationIndexEnum_Defeat1Otaku,
};

std::unordered_map<std::string, locationIndexEnum> enemyIDToLocationMap
{
	{ "Shrimp", locationIndexEnum_Defeat1Chumbud },
	{ "ShrimpQ", locationIndexEnum_Defeat1ChumbudQ },
	{ "Deadbeat", locationIndexEnum_Defeat1Deadbeat },
	{ "DeadbeatQ", locationIndexEnum_Defeat1DeadbeatQ },
	{ "Takodachi", locationIndexEnum_Defeat1Takodachi },
	{ "KFP", locationIndexEnum_Defeat1KFP },
	{ "Teamate", locationIndexEnum_Defeat1Teamate },
	{ "CursedBubba", locationIndexEnum_Defeat1CursedBubba },
	{ "SmollAme", locationIndexEnum_Defeat1SmolAme },
	{ "Brats", locationIndexEnum_Defeat1Brat },
	{ "HalloweenBae", locationIndexEnum_Defeat1BaeHalloween },
	{ "Hoomans", locationIndexEnum_Defeat1Hooman },
	{ "Saplings", locationIndexEnum_Defeat1Sapling },
	{ "Kronies", locationIndexEnum_Defeat1Kronie },
	{ "Sanalites", locationIndexEnum_Defeat1Sanalite },
	{ "Yatagarasu", locationIndexEnum_Defeat1Yatagarasu },
	{ "GuyRys", locationIndexEnum_Defeat1GuyRys },
	{ "Irystocrats", locationIndexEnum_Defeat1IrystocratLegacy },
	{ "BloomGloom", locationIndexEnum_Defeat1BloomAndGloom },
	{ "Sukonbu", locationIndexEnum_Defeat1Sukonbu },
	{ "FubuChun", locationIndexEnum_Defeat1FubuChun },
	{ "Oruyanke", locationIndexEnum_Defeat1Oruyanke },
	{ "Miteiru", locationIndexEnum_Defeat1Miteiru },
	{ "Fubuzilla", locationIndexEnum_Defeat1Fubura },
	{ "Miofa", locationIndexEnum_Defeat1Miofa },
	{ "Koronesuki", locationIndexEnum_Defeat1Koronesuki },
	{ "Onigiriya", locationIndexEnum_Defeat1Onigiriya },
	{ "Mikopi", locationIndexEnum_Defeat135P },
	{ "Kintoki", locationIndexEnum_Defeat1Kintoki },
	{ "Mikodanye", locationIndexEnum_Defeat1Mikodanye },
	{ "Soratomo", locationIndexEnum_Defeat1Soratomo },
	{ "Pioneer", locationIndexEnum_Defeat1Pioneer },
	{ "Hoshiyomi", locationIndexEnum_Defeat1Hoshiyomi },
	{ "Robosa", locationIndexEnum_Defeat1Robosa },
	{ "SSRB", locationIndexEnum_Defeat1SSRB },
	{ "Staff", locationIndexEnum_Defeat1Staff },
	{ "Achan", locationIndexEnum_Defeat1AChan },
	{ "Nodoka", locationIndexEnum_Defeat1HarusakiNodoka },
	{ "Matsurisu", locationIndexEnum_Defeat1Matsurisu },
	{ "Haaton", locationIndexEnum_Defeat1Haaton },
	{ "Kapumin", locationIndexEnum_Defeat1Kapumin },
	{ "ObakeChan", locationIndexEnum_Defeat1ObakeChan },
	{ "Rosetai", locationIndexEnum_Defeat1Rosetai },
	{ "Subatomo", locationIndexEnum_Defeat1Subatomo },
	{ "Shubangelion", locationIndexEnum_Defeat1Shubangelion },
	{ "Chocomate", locationIndexEnum_Defeat1Chocomate },
	{ "Chocolat", locationIndexEnum_Defeat1Chocolat },
	{ "Aquacrew", locationIndexEnum_Defeat1Aquacrew },
	{ "Shiokko", locationIndexEnum_Defeat1Shiokko },
	{ "Nakirigumi", locationIndexEnum_Defeat1Nakirigumi },
	{ "Poyoyo", locationIndexEnum_Defeat1Poyoyo },
	{ "Spiderchama", locationIndexEnum_Defeat1Spiderchama },
	{ "HalloweenMyth", locationIndexEnum_Defeat1HalloweenMyth },
	{ "Moonafic", locationIndexEnum_Defeat1Moonafic },
	{ "Moonabito", locationIndexEnum_Defeat1Moonabito },
	{ "Risuner", locationIndexEnum_Defeat1Risuner },
	{ "Riscot", locationIndexEnum_Defeat1Riscot },
	{ "Ioforia", locationIndexEnum_Defeat1Ioforia },
	{ "Zomrade", locationIndexEnum_Defeat1Zomrade },
	{ "Udin", locationIndexEnum_Defeat1Udin },
	{ "Merakyat", locationIndexEnum_Defeat1Merakyat },
	{ "Melfriend", locationIndexEnum_Defeat1Melfriend },
	{ "Kobokerz", locationIndexEnum_Defeat1Kobokerz },
	{ "Cilus", locationIndexEnum_Defeat1Cilus },
	{ "Zecretary", locationIndexEnum_Defeat1Zecretary },
	{ "Bazo", locationIndexEnum_Defeat1Bazo },
	{ "Pemaloe", locationIndexEnum_Defeat1Pemaloe },
	{ "Area15", locationIndexEnum_Defeat1Area15 },
	{ "Nousagi", locationIndexEnum_Defeat1Nousagi },
	{ "Ichimi", locationIndexEnum_Defeat1HoushouNoIchimin },
	{ "Elfriend", locationIndexEnum_Defeat1Elfriend },
	{ "ShiroganeKnight", locationIndexEnum_Defeat1KnightsOrderOfShirogane },
	{ "Tatsunoko", locationIndexEnum_Defeat1Tatsunoko },
	{ "Heimin", locationIndexEnum_Defeat1Heimin },
	{ "Upao", locationIndexEnum_Defeat1Upao },
	{ "Watamate", locationIndexEnum_Defeat1Watamate },
	{ "Kenzoku", locationIndexEnum_Defeat1TokoyamiKenzoku },
	{ "Luknight", locationIndexEnum_Defeat1LuKnight },
	{ "Nanoraaa", locationIndexEnum_Defeat1Nanoraaa },
	{ "Pekodam", locationIndexEnum_Defeat1Pekodam },
	{ "GoriEla", locationIndexEnum_Defeat1GoriEla },
	{ "Otaku", locationIndexEnum_Defeat1Otaku },
};

std::map<locationIndexEnum, std::vector<std::string>> locationToCharacterNameMap
{
	{ locationIndexEnum_AmeliaWastonStageClear, { "Amelia Watson" } },
	{ locationIndexEnum_AmeliaWastonGachikoi, { "Amelia Watson" } },
	{ locationIndexEnum_GawrGuraStageClear, { "Gawr Gura" } },
	{ locationIndexEnum_GawrGuraGachikoi, { "Gawr Gura" } },
	{ locationIndexEnum_NinomaeInanis10Minutes, { "Ninomae Inanis" } },
	{ locationIndexEnum_NinomaeInanisStageClear, { "Ninomae Inanis" } },
	{ locationIndexEnum_NinomaeInanisGachikoi, { "Ninomae Inanis" } },
	{ locationIndexEnum_TakanshiKiara10Minutes, { "Takanashi Kiara" } },
	{ locationIndexEnum_TakanshiKiaraStageClear, { "Takanashi Kiara" } },
	{ locationIndexEnum_TakanshiKiaraGachikoi, { "Takanashi Kiara" } },
	{ locationIndexEnum_MoriCalliope10Minutes, { "Mori Calliope" } },
	{ locationIndexEnum_MoriCalliopeStageClear, { "Mori Calliope" } },
	{ locationIndexEnum_MoriCalliopeGachikoi, { "Mori Calliope" } },
	{ locationIndexEnum_HakosBaelz10Minutes, { "Hakos Baelz" } },
	{ locationIndexEnum_HakosBaelzStageClear, { "Hakos Baelz" } },
	{ locationIndexEnum_HakosBaelzGachikoi, { "Hakos Baelz" } },
	{ locationIndexEnum_OuroKroniiStageClear, { "Ouro Kronii" } },
	{ locationIndexEnum_OuroKroniiGachikoi, { "Ouro Kronii" } },
	{ locationIndexEnum_CeresFaunaStageClear, { "Ceres Fauna" } },
	{ locationIndexEnum_CeresFaunaGachikoi, { "Ceres Fauna" } },
	{ locationIndexEnum_NanashiMumeiStageClear, { "Nanashi Mumei" } },
	{ locationIndexEnum_NanashiMumeiGachikoi, { "Nanashi Mumei" } },
	{ locationIndexEnum_TsukumoSana10Minutes, { "Tsukumo Sana" } },
	{ locationIndexEnum_TsukumoSanaStageClear, { "Tsukumo Sana" } },
	{ locationIndexEnum_TsukumoSanaGachikoi, { "Tsukumo Sana" } },
	{ locationIndexEnum_IRyS10Minutes, { "IRyS" } },
	{ locationIndexEnum_IRySStageClear, { "IRyS" } },
	{ locationIndexEnum_IRySGachikoi, { "IRyS" } },
	{ locationIndexEnum_ShirakamiFubukiStageClear, { "Shirakami Fubuki" } },
	{ locationIndexEnum_ShirakamiFubukiGachikoi, { "Shirakami Fubuki" } },
	{ locationIndexEnum_OokamiMioStageClear, { "Ookami Mio" } },
	{ locationIndexEnum_OokamiMioGachikoi, { "Ookami Mio" } },
	{ locationIndexEnum_NekomataOkayuStageClear, { "Nekomata Okayu" } },
	{ locationIndexEnum_NekomataOkayuGachikoi, { "Nekomata Okayu" } },
	{ locationIndexEnum_InugamiKorone10Minutes, { "Inugami Korone" } },
	{ locationIndexEnum_InugamiKoroneStageClear, { "Inugami Korone" } },
	{ locationIndexEnum_InugamiKoroneGachikoi, { "Inugami Korone" } },
	{ locationIndexEnum_TokinoSoraStageClear, { "Tokino Sora" } },
	{ locationIndexEnum_TokinoSoraGachikoi, { "Tokino Sora" } },
	{ locationIndexEnum_AZkiStageClear, { "AZki" } },
	{ locationIndexEnum_AZkiGachikoi, { "AZki" } },
	{ locationIndexEnum_RobocoStageClear, { "Roboco-san" } },
	{ locationIndexEnum_RobocoGachikoi, { "Roboco-san" } },
	{ locationIndexEnum_HoshimachiSuiseiStageClear, { "Hoshimachi Suisei" } },
	{ locationIndexEnum_HoshimachiSuiseiGachikoi, { "Hoshimachi Suisei" } },
	{ locationIndexEnum_SakuraMikoStageClear, { "Sakura Miko" } },
	{ locationIndexEnum_SakuraMikoGachikoi, { "Sakura Miko" } },
	{ locationIndexEnum_AkaiHaatoStageClear, { "Akai Haato" } },
	{ locationIndexEnum_AkaiHaatoGachikoi, { "Akai Haato" } },
	{ locationIndexEnum_YozoraMelStageClear, { "Yozora Mel" } },
	{ locationIndexEnum_YozoraMelGachikoi, { "Yozora Mel" } },
	{ locationIndexEnum_NatsuiroMatsuriStageClear, { "Natsuiro Matsuri" } },
	{ locationIndexEnum_NatsuiroMatsuriGachikoi, { "Natsuiro Matsuri" } },
	{ locationIndexEnum_AkiRosenthalStageClear, { "Aki Rosenthal" } },
	{ locationIndexEnum_AkiRosenthalGachikoi, { "Aki Rosenthal" } },
	{ locationIndexEnum_YuzukiChocoStageClear, { "Yuzuki Choco" } },
	{ locationIndexEnum_YuzukiChocoGachikoi, { "Yuzuki Choco" } },
	{ locationIndexEnum_OozoraSubaruStageClear, { "Oozora Subaru" } },
	{ locationIndexEnum_OozoraSubaruGachikoi, { "Oozora Subaru" } },
	{ locationIndexEnum_MurasakiShion10Minutes, { "Murasaki Shion" } },
	{ locationIndexEnum_MurasakiShionStageClear, { "Murasaki Shion" } },
	{ locationIndexEnum_MurasakiShionGachikoi, { "Murasaki Shion" } },
	{ locationIndexEnum_NakiriAyameStageClear, { "Nakiri Ayame" } },
	{ locationIndexEnum_NakiriAyameGachikoi, { "Nakiri Ayame" } },
	{ locationIndexEnum_MinatoAquaStageClear, { "Minato Aqua" } },
	{ locationIndexEnum_MinatoAquaGachikoi, { "Minato Aqua" } },
	{ locationIndexEnum_MoonaHoshinovaStageClear, { "Moona Hoshinova" } },
	{ locationIndexEnum_MoonaHoshinovaGachikoi, { "Moona Hoshinova" } },
	{ locationIndexEnum_AiraniIofifteenStageClear, { "Airani Iofifteen" } },
	{ locationIndexEnum_AiraniIofifteenGachikoi, { "Airani Iofifteen" } },
	{ locationIndexEnum_AyundaRisuStageClear, { "Ayunda Risu" } },
	{ locationIndexEnum_AyundaRisuGachikoi, { "Ayunda Risu" } },
	{ locationIndexEnum_KureijiOllieStageClear, { "Kureiji Ollie" } },
	{ locationIndexEnum_KureijiOllie10Minutes, { "Kureiji Ollie" } },
	{ locationIndexEnum_KureijiOllieGachikoi, { "Kureiji Ollie" } },
	{ locationIndexEnum_PavoliaReineStageClear, { "Pavolia Reine" } },
	{ locationIndexEnum_PavoliaReineGachikoi, { "Pavolia Reine" } },
	{ locationIndexEnum_AnyaMelfissaStageClear, { "Anya Melfissa" } },
	{ locationIndexEnum_AnyaMelfissaGachikoi, { "Anya Melfissa" } },
	{ locationIndexEnum_KoboKanaeruStageClear, { "Kobo Kanaeru" } },
	{ locationIndexEnum_KoboKanaeruGachikoi, { "Kobo Kanaeru" } },
	{ locationIndexEnum_KaelaKovalskiaStageClear, { "Kaela Kovalskia" } },
	{ locationIndexEnum_KaelaKovalskiaGachikoi, { "Kaela Kovalskia" } },
	{ locationIndexEnum_VestiaZeta10Minutes, { "Vestia Zeta" } },
	{ locationIndexEnum_VestiaZetaStageClear, { "Vestia Zeta" } },
	{ locationIndexEnum_VestiaZetaGachikoi, { "Vestia Zeta" } },
	{ locationIndexEnum_UsadaPekoraStageClear, { "Usada Pekora" } },
	{ locationIndexEnum_UsadaPekoraGachikoi, { "Usada Pekora" } },
	{ locationIndexEnum_ShiroganeNoelStageClear, { "Shirogane Noel" } },
	{ locationIndexEnum_ShiroganeNoelGachikoi, { "Shirogane Noel" } },
	{ locationIndexEnum_ShiranuiFlareStageClear, { "Shiranui Flare" } },
	{ locationIndexEnum_ShiranuiFlareGachikoi, { "Shiranui Flare" } },
	{ locationIndexEnum_HoushouMarineStageClear, { "Houshou Marine" } },
	{ locationIndexEnum_HoushouMarineGachikoi, { "Houshou Marine" } },
	{ locationIndexEnum_KiryuCocoStageClear, { "Kiryu Coco" } },
	{ locationIndexEnum_KiryuCocoGachikoi, { "Kiryu Coco" } },
	{ locationIndexEnum_AmaneKanataStageClear, { "Amane Kanata" } },
	{ locationIndexEnum_AmaneKanataGachikoi, { "Amane Kanata" } },
	{ locationIndexEnum_TsunomakiWatameStageClear, { "Tsunomaki Watame" } },
	{ locationIndexEnum_TsunomakiWatameGachikoi, { "Tsunomaki Watame" } },
	{ locationIndexEnum_TokoyamiTowaStageClear, { "Tokoyami Towa" } },
	{ locationIndexEnum_TokoyamiTowaGachikoi, { "Tokoyami Towa" } },
	{ locationIndexEnum_HimemoriLunaStageClear, { "Himemori Luna" } },
	{ locationIndexEnum_HimemoriLunaGachikoi, { "Himemori Luna" } },
	{ locationIndexEnum_UnlockAllCharacters, { "All" } },
	{ locationIndexEnum_CuttingBoard10Minutes, { "Amane Kanata", "Gawr Gura", "Hoshimachi Suisei", "Kobo Kanaeru", "Kureiji Ollie", "Murasaki Shion", "Natsuiro Matsuri", "Ninomae Inanis" } },
	{ locationIndexEnum_IofiSpecial20Seconds, { "Airani Iofifteen" } },
	{ locationIndexEnum_PetBubba, { "Amelia Watson" } },
	{ locationIndexEnum_GetSomeHelp, { "All" } },
};

std::unordered_map<goalIndexEnum, std::unordered_set<locationIndexEnum>> goalIndexToLocationListMap
{
	{
		goalIndexEnum_BeatAllNormalStages,
		{
			locationIndexEnum_DefeatStage1Boss,
			locationIndexEnum_DefeatStage2Boss,
			locationIndexEnum_DefeatStage3Boss,
			locationIndexEnum_DefeatStage4Boss,
			locationIndexEnum_DefeatStage5Boss
		}
	},
	{
		goalIndexEnum_BeatAllHardStages,
		{
			locationIndexEnum_DefeatStage1HardBoss,
			locationIndexEnum_DefeatStage2HardBoss,
			locationIndexEnum_DefeatStage3HardBoss,
			locationIndexEnum_DefeatStage4HardBoss
		}
	},
	{
		goalIndexEnum_BuyAllShopUpgrades,
		{
			locationIndexEnum_GrowthShop3,
			locationIndexEnum_RerollShop10,
			locationIndexEnum_EliminateShop10,
			locationIndexEnum_HoldShop5,
			locationIndexEnum_CustomizeShop,
			locationIndexEnum_SupportsShop,
			locationIndexEnum_MaterialFindShop,
			locationIndexEnum_StampsShop,
			locationIndexEnum_EnchantShop,
			locationIndexEnum_FandomShop,
			locationIndexEnum_FanLetterShop,
			locationIndexEnum_MaxHPShop10,
			locationIndexEnum_ATKShop10,
			locationIndexEnum_SPDShop10,
			locationIndexEnum_CritShop5,
			locationIndexEnum_PickUpRangeShop10,
			locationIndexEnum_HasteShop5,
			locationIndexEnum_RegenShop5,
			locationIndexEnum_DefenseShop5,
			locationIndexEnum_SpecialCDRShop5,
			locationIndexEnum_SkillUpShop10,
			locationIndexEnum_EXPGainShop5,
			locationIndexEnum_FoodShop5,
			locationIndexEnum_MoneyGainShop10,
			locationIndexEnum_EnhancementShop5,
			locationIndexEnum_MarketingShop5,
		}
	},
	{
		goalIndexEnum_HololiveMemberStageClear,
		{
			locationIndexEnum_AmeliaWastonStageClear,
			locationIndexEnum_GawrGuraStageClear,
			locationIndexEnum_NinomaeInanisStageClear,
			locationIndexEnum_TakanshiKiaraStageClear,
			locationIndexEnum_MoriCalliopeStageClear,
			locationIndexEnum_HakosBaelzStageClear,
			locationIndexEnum_OuroKroniiStageClear,
			locationIndexEnum_CeresFaunaStageClear,
			locationIndexEnum_NanashiMumeiStageClear,
			locationIndexEnum_TsukumoSanaStageClear,
			locationIndexEnum_IRySStageClear,
			locationIndexEnum_ShirakamiFubukiStageClear,
			locationIndexEnum_OokamiMioStageClear,
			locationIndexEnum_NekomataOkayuStageClear,
			locationIndexEnum_InugamiKoroneStageClear,
			locationIndexEnum_TokinoSoraStageClear,
			locationIndexEnum_AZkiStageClear,
			locationIndexEnum_RobocoStageClear,
			locationIndexEnum_HoshimachiSuiseiStageClear,
			locationIndexEnum_SakuraMikoStageClear,
			locationIndexEnum_AkaiHaatoStageClear,
			locationIndexEnum_YozoraMelStageClear,
			locationIndexEnum_NatsuiroMatsuriStageClear,
			locationIndexEnum_AkiRosenthalStageClear,
			locationIndexEnum_YuzukiChocoStageClear,
			locationIndexEnum_OozoraSubaruStageClear,
			locationIndexEnum_MurasakiShionStageClear,
			locationIndexEnum_NakiriAyameStageClear,
			locationIndexEnum_MinatoAquaStageClear,
			locationIndexEnum_MoonaHoshinovaStageClear,
			locationIndexEnum_AiraniIofifteenStageClear,
			locationIndexEnum_AyundaRisuStageClear,
			locationIndexEnum_KureijiOllieStageClear,
			locationIndexEnum_PavoliaReineStageClear,
			locationIndexEnum_AnyaMelfissaStageClear,
			locationIndexEnum_KoboKanaeruStageClear,
			locationIndexEnum_KaelaKovalskiaStageClear,
			locationIndexEnum_VestiaZetaStageClear,
			locationIndexEnum_UsadaPekoraStageClear,
			locationIndexEnum_ShiroganeNoelStageClear,
			locationIndexEnum_ShiranuiFlareStageClear,
			locationIndexEnum_HoushouMarineStageClear,
			locationIndexEnum_KiryuCocoStageClear,
			locationIndexEnum_AmaneKanataStageClear,
			locationIndexEnum_TsunomakiWatameStageClear,
			locationIndexEnum_TokoyamiTowaStageClear,
			locationIndexEnum_HimemoriLunaStageClear,
		}
	},
	{
		goalIndexEnum_Achievement,
		{
			locationIndexEnum_AmeliaWastonStageClear,
			locationIndexEnum_AmeliaWastonGachikoi,
			locationIndexEnum_GawrGuraStageClear,
			locationIndexEnum_GawrGuraGachikoi,
			locationIndexEnum_NinomaeInanis10Minutes,
			locationIndexEnum_NinomaeInanisStageClear,
			locationIndexEnum_NinomaeInanisGachikoi,
			locationIndexEnum_TakanshiKiara10Minutes,
			locationIndexEnum_TakanshiKiaraStageClear,
			locationIndexEnum_TakanshiKiaraGachikoi,
			locationIndexEnum_MoriCalliope10Minutes,
			locationIndexEnum_MoriCalliopeStageClear,
			locationIndexEnum_MoriCalliopeGachikoi,
			locationIndexEnum_HakosBaelz10Minutes,
			locationIndexEnum_HakosBaelzStageClear,
			locationIndexEnum_HakosBaelzGachikoi,
			locationIndexEnum_OuroKroniiStageClear,
			locationIndexEnum_OuroKroniiGachikoi,
			locationIndexEnum_CeresFaunaStageClear,
			locationIndexEnum_CeresFaunaGachikoi,
			locationIndexEnum_NanashiMumeiStageClear,
			locationIndexEnum_NanashiMumeiGachikoi,
			locationIndexEnum_TsukumoSana10Minutes,
			locationIndexEnum_TsukumoSanaStageClear,
			locationIndexEnum_TsukumoSanaGachikoi,
			locationIndexEnum_IRyS10Minutes,
			locationIndexEnum_IRySStageClear,
			locationIndexEnum_IRySGachikoi,
			locationIndexEnum_ShirakamiFubukiStageClear,
			locationIndexEnum_ShirakamiFubukiGachikoi,
			locationIndexEnum_OokamiMioStageClear,
			locationIndexEnum_OokamiMioGachikoi,
			locationIndexEnum_NekomataOkayuStageClear,
			locationIndexEnum_NekomataOkayuGachikoi,
			locationIndexEnum_InugamiKorone10Minutes,
			locationIndexEnum_InugamiKoroneStageClear,
			locationIndexEnum_InugamiKoroneGachikoi,
			locationIndexEnum_TokinoSoraStageClear,
			locationIndexEnum_TokinoSoraGachikoi,
			locationIndexEnum_AZkiStageClear,
			locationIndexEnum_AZkiGachikoi,
			locationIndexEnum_RobocoStageClear,
			locationIndexEnum_RobocoGachikoi,
			locationIndexEnum_HoshimachiSuiseiStageClear,
			locationIndexEnum_HoshimachiSuiseiGachikoi,
			locationIndexEnum_SakuraMikoStageClear,
			locationIndexEnum_SakuraMikoGachikoi,
			locationIndexEnum_AkaiHaatoStageClear,
			locationIndexEnum_AkaiHaatoGachikoi,
			locationIndexEnum_YozoraMelStageClear,
			locationIndexEnum_YozoraMelGachikoi,
			locationIndexEnum_NatsuiroMatsuriStageClear,
			locationIndexEnum_NatsuiroMatsuriGachikoi,
			locationIndexEnum_AkiRosenthalStageClear,
			locationIndexEnum_AkiRosenthalGachikoi,
			locationIndexEnum_YuzukiChocoStageClear,
			locationIndexEnum_YuzukiChocoGachikoi,
			locationIndexEnum_OozoraSubaruStageClear,
			locationIndexEnum_OozoraSubaruGachikoi,
			locationIndexEnum_MurasakiShion10Minutes,
			locationIndexEnum_MurasakiShionStageClear,
			locationIndexEnum_MurasakiShionGachikoi,
			locationIndexEnum_NakiriAyameStageClear,
			locationIndexEnum_NakiriAyameGachikoi,
			locationIndexEnum_MinatoAquaStageClear,
			locationIndexEnum_MinatoAquaGachikoi,
			locationIndexEnum_MoonaHoshinovaStageClear,
			locationIndexEnum_MoonaHoshinovaGachikoi,
			locationIndexEnum_AiraniIofifteenStageClear,
			locationIndexEnum_AiraniIofifteenGachikoi,
			locationIndexEnum_AyundaRisuStageClear,
			locationIndexEnum_AyundaRisuGachikoi,
			locationIndexEnum_KureijiOllieStageClear,
			locationIndexEnum_KureijiOllie10Minutes,
			locationIndexEnum_KureijiOllieGachikoi,
			locationIndexEnum_PavoliaReineStageClear,
			locationIndexEnum_PavoliaReineGachikoi,
			locationIndexEnum_AnyaMelfissaStageClear,
			locationIndexEnum_AnyaMelfissaGachikoi,
			locationIndexEnum_KoboKanaeruStageClear,
			locationIndexEnum_KoboKanaeruGachikoi,
			locationIndexEnum_KaelaKovalskiaStageClear,
			locationIndexEnum_KaelaKovalskiaGachikoi,
			locationIndexEnum_VestiaZeta10Minutes,
			locationIndexEnum_VestiaZetaStageClear,
			locationIndexEnum_VestiaZetaGachikoi,
			locationIndexEnum_UsadaPekoraStageClear,
			locationIndexEnum_UsadaPekoraGachikoi,
			locationIndexEnum_ShiroganeNoelStageClear,
			locationIndexEnum_ShiroganeNoelGachikoi,
			locationIndexEnum_ShiranuiFlareStageClear,
			locationIndexEnum_ShiranuiFlareGachikoi,
			locationIndexEnum_HoushouMarineStageClear,
			locationIndexEnum_HoushouMarineGachikoi,
			locationIndexEnum_KiryuCocoStageClear,
			locationIndexEnum_KiryuCocoGachikoi,
			locationIndexEnum_AmaneKanataStageClear,
			locationIndexEnum_AmaneKanataGachikoi,
			locationIndexEnum_TsunomakiWatameStageClear,
			locationIndexEnum_TsunomakiWatameGachikoi,
			locationIndexEnum_TokoyamiTowaStageClear,
			locationIndexEnum_TokoyamiTowaGachikoi,
			locationIndexEnum_HimemoriLunaStageClear,
			locationIndexEnum_HimemoriLunaGachikoi,
			locationIndexEnum_FirstGame,
			locationIndexEnum_DefeatFubura,
			locationIndexEnum_DefeatStage1Boss,
			locationIndexEnum_DefeatStage2Boss,
			locationIndexEnum_DefeatStage3Boss,
			locationIndexEnum_DefeatStage4Boss,
			locationIndexEnum_DefeatStage5Boss,
			locationIndexEnum_DefeatStage1HardBoss,
			locationIndexEnum_DefeatStage2HardBoss,
			locationIndexEnum_DefeatStage3HardBoss,
			locationIndexEnum_DefeatStage4HardBoss,
			locationIndexEnum_ClearTimeMode,
			locationIndexEnum_UnlockAllCharacters,
			locationIndexEnum_UseSpecial,
			locationIndexEnum_DestroyYagooStatue,
			locationIndexEnum_UseAnvil,
			locationIndexEnum_CuttingBoard10Minutes,
			locationIndexEnum_UsePlugTypeAsacoco,
			locationIndexEnum_5000Coins,
			locationIndexEnum_1000000Coins,
			locationIndexEnum_UseSake,
			locationIndexEnum_Level50,
			locationIndexEnum_Level100,
			locationIndexEnum_Defeat5000,
			locationIndexEnum_LoseWithHalu,
			locationIndexEnum_Eat50Hamburgers,
			locationIndexEnum_Deal1000Damage,
			locationIndexEnum_Deal10000Damage,
			locationIndexEnum_NoMove,
			locationIndexEnum_10Minutes,
			locationIndexEnum_NoSpecial,
			locationIndexEnum_UseSuperChattoTime,
			locationIndexEnum_PetBubba,
			locationIndexEnum_Get4Collabs,
			locationIndexEnum_Take500Damage,
			locationIndexEnum_EnhanceAWeapon,
			locationIndexEnum_DefeatYagoo,
			locationIndexEnum_DefeatGoldYagoo,
			locationIndexEnum_DefeatSilverYagoo,
			locationIndexEnum_LoseToYagoo,
			locationIndexEnum_SuperBox,
			locationIndexEnum_DropSuperItem,
			locationIndexEnum_ClearHardcore,
			locationIndexEnum_10Enhance,
			locationIndexEnum_MainWeaponOnly,
			locationIndexEnum_Fail5Enhance,
			locationIndexEnum_Fail1To2Enhance,
			locationIndexEnum_ClearHaluLevel5,
			locationIndexEnum_30MinutesHaluLevel5,
			locationIndexEnum_DefeatBossUnder10Seconds,
			locationIndexEnum_LeaveBossAlive5Minutes,
			locationIndexEnum_LevelUp5Times1Second,
			locationIndexEnum_CompleteArmory,
			locationIndexEnum_WatchCredits,
			locationIndexEnum_100Crit,
			locationIndexEnum_1MillionScore,
			locationIndexEnum_WatchTV10Seconds,
			locationIndexEnum_NoDamage5Minutes,
			locationIndexEnum_HoloHouse,
			locationIndexEnum_AnnoyMember,
			locationIndexEnum_HarvestPlant,
			locationIndexEnum_CatchShinyFish,
			locationIndexEnum_StealFish,
			locationIndexEnum_CookDish,
			locationIndexEnum_Fish10Combo,
			locationIndexEnum_Fish50Combo,
			locationIndexEnum_CatchEveryFish,
			locationIndexEnum_HarvestEveryCrop,
			locationIndexEnum_MaxLevelWorker,
			locationIndexEnum_ManagerLevel4,
			locationIndexEnum_RetireWorker,
			locationIndexEnum_Collect10000CoinsWorkers,
			locationIndexEnum_Huh,
			locationIndexEnum_NoItems,
			locationIndexEnum_GoldHammer,
			locationIndexEnum_NoSkill,
			locationIndexEnum_HasteUp10,
			locationIndexEnum_IofiSpecial20Seconds,
			locationIndexEnum_FirstOptionOnly,
			locationIndexEnum_HardNoProjectiles,
			locationIndexEnum_MainWeaponLevel1Only,
			locationIndexEnum_ClearHardNoHealItems,
			locationIndexEnum_500HP,
			locationIndexEnum_UsadaCasino,
			locationIndexEnum_WinWorkerRace,
			locationIndexEnum_WinWorkerFight,
			locationIndexEnum_Get100000UsaChips,
			locationIndexEnum_GetAPet,
			locationIndexEnum_LoseWith0UsaChips,
			locationIndexEnum_10FanLetters,
			locationIndexEnum_Stage4HardNoQuestionsWrong,
			locationIndexEnum_WinJackpot,
			locationIndexEnum_Sell10Stamps,
			locationIndexEnum_500PickUpRange,
			locationIndexEnum_3DeathChickenFeather,
			locationIndexEnum_ClearTowerOfSuffering,
			locationIndexEnum_GetSomeHelp,
		}
	},
};